/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.view;

import com.grocery.bean.CustomerMaster;
import com.grocery.bean.CustomerPartialPayment;
import com.grocery.bean.SaleMaster;
import com.grocery.dimension.SetDimension;
import com.grocery.query.CustomerMasterQuery;
import com.grocery.query.CustomerPartialPaymentQuery;
import com.grocery.query.SaleMasterQuery;
import com.grocery.read.MessageFormat;
import com.grocery.read.ReadFile;
import com.grocery.util.MyConnection;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Admin
 */
public class CustomerPartialPaymentView extends javax.swing.JInternalFrame {

    private JDesktopPane jDesktopPane;
    private SaleMaster saleMaster;
    private CustomerPartialPayment customerPartialPayment;
    private Date date = new Date();
    
    public CustomerPartialPaymentView(JDesktopPane jDesktopPane, SaleMaster saleMaster, CustomerPartialPayment customerPartialPayment, String counter) {
        initComponents();
        saleDate.setDate(date);
        this.jDesktopPane = jDesktopPane;
        this.saleMaster = saleMaster;
        this.customerPartialPayment = customerPartialPayment;
        billId.setText(String.valueOf(saleMaster.getId()));
        this.counter.setText(counter);
        billAmount.setText(String.valueOf(saleMaster.getBillAmount()));
        discount.setText(String.valueOf(saleMaster.getDiscount()));
        finalAmount.setText(String.valueOf(saleMaster.getFinalBillAmount()));
        paymentMode.setText(customerPartialPayment.getPaymentMode());
        number.setText(customerPartialPayment.getChequeOrCardNumber());
        if(customerPartialPayment.getChequeDate() != null)
            chequeDate.setDate(customerPartialPayment.getChequeDate());
        bank.setText(customerPartialPayment.getBank());
        remark.setText(saleMaster.getRemark());
        reference.setText(saleMaster.getReference());
        
        jPanelCustomer.setVisible(false);
        CustomerMaster customerMaster = new CustomerMaster();
        loadCustomer(customerMaster);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        customer = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jPanelCustomer = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        newCustomer = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        billId = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        counter = new javax.swing.JTextField();
        billAmount = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        saleDate = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        discount = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        finalAmount = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        paymentMode = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        chequeDate = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        bank = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        paidAmount = new javax.swing.JFormattedTextField();
        pay = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        remark = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelDues = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        gstNumber = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        reference = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Customer:");

        customer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Customer Details:");

        jLabel19.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Contact:");

        contact.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contact.setText("N/A");
        contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactFocusLost(evt);
            }
        });
        contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactKeyTyped(evt);
            }
        });

        jPanelCustomer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Enter the Customer's name:");

        newCustomer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        newCustomer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        newCustomer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCustomerFocusGained(evt);
            }
        });
        newCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newCustomerKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel21.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Address:");

        address.setColumns(20);
        address.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        address.setRows(5);
        address.setText("N/A");
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(address);

        jLabel25.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Bill Details:");

        jLabel22.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Bill Id:");

        billId.setEditable(false);
        billId.setBackground(new java.awt.Color(255, 255, 153));
        billId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        billId.setForeground(new java.awt.Color(255, 0, 0));
        billId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        billId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                billIdFocusGained(evt);
            }
        });
        billId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billIdActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Counter:");

        counter.setEditable(false);
        counter.setBackground(new java.awt.Color(255, 255, 153));
        counter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        counter.setForeground(new java.awt.Color(255, 0, 0));
        counter.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        counter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                counterFocusGained(evt);
            }
        });
        counter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counterActionPerformed(evt);
            }
        });

        billAmount.setEditable(false);
        billAmount.setBackground(new java.awt.Color(255, 255, 153));
        billAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        billAmount.setForeground(new java.awt.Color(255, 0, 0));
        billAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        billAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                billAmountFocusGained(evt);
            }
        });
        billAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billAmountActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Bill Amount:");

        jLabel27.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("Date:");

        saleDate.setEnabled(false);
        saleDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Discount:");

        discount.setEditable(false);
        discount.setBackground(new java.awt.Color(255, 255, 153));
        discount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        discount.setForeground(new java.awt.Color(255, 0, 0));
        discount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        discount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                discountFocusGained(evt);
            }
        });
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Final Amount:");

        finalAmount.setEditable(false);
        finalAmount.setBackground(new java.awt.Color(255, 255, 153));
        finalAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        finalAmount.setForeground(new java.awt.Color(102, 255, 51));
        finalAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        finalAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                finalAmountFocusGained(evt);
            }
        });
        finalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalAmountActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Payment Mode:");

        paymentMode.setEditable(false);
        paymentMode.setBackground(new java.awt.Color(255, 255, 153));
        paymentMode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paymentMode.setForeground(new java.awt.Color(255, 0, 0));
        paymentMode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paymentMode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentModeFocusGained(evt);
            }
        });
        paymentMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentModeActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Cheque/Card #:");

        number.setEditable(false);
        number.setBackground(new java.awt.Color(255, 255, 153));
        number.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        number.setForeground(new java.awt.Color(255, 0, 0));
        number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberFocusGained(evt);
            }
        });
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("Cheque Date:");

        chequeDate.setEnabled(false);
        chequeDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("Bank:");

        bank.setEditable(false);
        bank.setBackground(new java.awt.Color(255, 255, 153));
        bank.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bank.setForeground(new java.awt.Color(255, 0, 0));
        bank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bank.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankFocusGained(evt);
            }
        });
        bank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Paid Amount:");

        paidAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        paidAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paidAmount.setText("0.00");
        paidAmount.setToolTipText("");
        paidAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paidAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paidAmountKeyPressed(evt);
            }
        });

        pay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pay.setMnemonic(KeyEvent.VK_P);
        pay.setText("Pay");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        pay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                payKeyPressed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel.setMnemonic(KeyEvent.VK_C);
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cancelKeyPressed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("Remark:");

        remark.setEditable(false);
        remark.setBackground(new java.awt.Color(255, 255, 153));
        remark.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        remark.setForeground(new java.awt.Color(255, 0, 0));
        remark.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Previous Dues:");

        jLabelDues.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDues.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDues.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDues.setText("0.00");

        jLabel36.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("GST No:");

        gstNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        gstNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gstNumber.setText("N/A");
        gstNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gstNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gstNumberFocusLost(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Reference:");

        reference.setEditable(false);
        reference.setBackground(new java.awt.Color(255, 255, 153));
        reference.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reference.setForeground(new java.awt.Color(255, 0, 0));
        reference.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        reference.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                referenceFocusGained(evt);
            }
        });
        reference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101)
                                        .addComponent(gstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelDues, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(billId)
                                    .addComponent(finalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(61, 61, 61)
                                .addComponent(bank)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paymentMode)
                                    .addComponent(counter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(32, 32, 32)
                                .addComponent(reference)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel26)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(number)
                            .addComponent(billAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(remark))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chequeDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(383, 383, 383))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(saleDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(billId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(counter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(finalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(paymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(reference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(billAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(chequeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(paidAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pay)
                            .addComponent(cancel)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDues, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        if(customer.getItemCount() > 0)
        {
            address.setText("N/A");
            contact.setText("N/A");
            gstNumber.setText("N/A");
            jPanelCustomer.setVisible(false);
            newCustomer.setText("");
            jLabelDues.setText("0.00");
             
            if(customer.getSelectedItem().toString().equalsIgnoreCase("add new"))
                jPanelCustomer.setVisible(true);
            else
            {
                CustomerMaster customerMaster = new CustomerMaster();
                customerMaster.setName(customer.getSelectedItem().toString());
                getDetails(customerMaster);
            }
            
        }
    }//GEN-LAST:event_customerActionPerformed

    private void contactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
        evt.consume();
    }//GEN-LAST:event_contactKeyTyped

    private void newCustomerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCustomerFocusGained
        newCustomer.selectAll();
    }//GEN-LAST:event_newCustomerFocusGained

    private void newCustomerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newCustomerKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c == KeyEvent.VK_BACK_SPACE)|| (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_SPACE) || c == '.' || c == '-'))
        evt.consume();
    }//GEN-LAST:event_newCustomerKeyTyped

    private void billIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billIdFocusGained

    }//GEN-LAST:event_billIdFocusGained

    private void billIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billIdActionPerformed

    private void counterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_counterFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_counterFocusGained

    private void counterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_counterActionPerformed

    private void billAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billAmountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_billAmountFocusGained

    private void billAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billAmountActionPerformed

    private void discountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_discountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_discountFocusGained

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountActionPerformed

    private void finalAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_finalAmountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_finalAmountFocusGained

    private void finalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalAmountActionPerformed

    private void paymentModeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentModeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentModeFocusGained

    private void paymentModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentModeActionPerformed

    private void numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_numberFocusGained

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void bankFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bankFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_bankFocusGained

    private void bankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankActionPerformed

    private void contactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFocusLost
        if(contact.getText().trim().isEmpty())
            contact.setText("N/A");
    }//GEN-LAST:event_contactFocusLost

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        if(address.getText().trim().isEmpty())
            address.setText("N/A");
    }//GEN-LAST:event_addressFocusLost

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        pay();
    }//GEN-LAST:event_payActionPerformed

    private void paidAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidAmountKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            pay();
    }//GEN-LAST:event_paidAmountKeyPressed

    private void payKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            pay();
    }//GEN-LAST:event_payKeyPressed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        SalesPageView storeDetails = new SalesPageView(jDesktopPane, saleMaster, customerPartialPayment, counter.getText());
        storeDetails.setTitle("Sales Page");
        jDesktopPane.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane, storeDetails);
        storeDetails.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void cancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cancelKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
           SalesPageView storeDetails = new SalesPageView(jDesktopPane, saleMaster, customerPartialPayment, counter.getText());
            storeDetails.setTitle("Sales Page");
            jDesktopPane.add(storeDetails);
            SetDimension setDimension = new SetDimension();
            setDimension.setInternalFrameLocation(jDesktopPane, storeDetails);
            storeDetails.setVisible(true); 
        }
    }//GEN-LAST:event_cancelKeyPressed

    private void gstNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gstNumberFocusLost
        if(gstNumber.getText().trim().isEmpty())
            gstNumber.setText("N/A");
    }//GEN-LAST:event_gstNumberFocusLost

    private void gstNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gstNumberFocusGained
        gstNumber.selectAll();
    }//GEN-LAST:event_gstNumberFocusGained

    private void referenceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_referenceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceFocusGained

    private void referenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField bank;
    private javax.swing.JTextField billAmount;
    private javax.swing.JTextField billId;
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JDateChooser chequeDate;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField counter;
    private javax.swing.JComboBox<String> customer;
    private javax.swing.JTextField discount;
    private javax.swing.JTextField finalAmount;
    private javax.swing.JTextField gstNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabelDues;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField newCustomer;
    private javax.swing.JTextField number;
    private javax.swing.JFormattedTextField paidAmount;
    private javax.swing.JButton pay;
    private javax.swing.JTextField paymentMode;
    private javax.swing.JTextField reference;
    private javax.swing.JTextField remark;
    private com.toedter.calendar.JDateChooser saleDate;
    // End of variables declaration//GEN-END:variables

    private void getDetails(CustomerMaster customerMaster) 
    {
        
        CustomerMasterQuery customerMasterQuery = new CustomerMasterQuery();
        
        List<CustomerMaster> list = customerMasterQuery.getCustomer(customerMaster);
        
        for(CustomerMaster cm: list)
        {
            contact.setText(cm.getContact());
            address.setText(cm.getAddress());
            jLabelDues.setText(String.valueOf(cm.getBalance()));
            gstNumber.setText(cm.getGstNumber());
        }
    }

    private void loadCustomer(CustomerMaster customerMaster) 
    {
        CustomerMasterQuery customerMasterQuery = new CustomerMasterQuery();
        DefaultComboBoxModel defaultComboBoxModel = (DefaultComboBoxModel)customer.getModel();
        defaultComboBoxModel.removeAllElements();
        
        defaultComboBoxModel.addElement("--Select--");
        defaultComboBoxModel.addElement("Add New");
        List<CustomerMaster> list = customerMasterQuery.getCustomer(customerMaster);
        
        for(CustomerMaster cm: list)
            defaultComboBoxModel.addElement(cm.getName());
        
        customer.setModel(defaultComboBoxModel);
    }

    private void pay() 
    {
        CustomerMaster customerMaster = new CustomerMaster();
        CustomerMasterQuery customerMasterQuery = new CustomerMasterQuery();
        
        if(paidAmount.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please enter the Paid Amount"), "Error Message", JOptionPane.ERROR_MESSAGE);
            paidAmount.requestFocus();
            return;
        }
        
        if(!(paymentMode.getText().trim().equalsIgnoreCase("cash")))
        {
            if(Float.parseFloat(paidAmount.getText().trim()) == 0)
            {
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Paid Amount can't be Zero for Cheque/Card"), "Error Message", JOptionPane.ERROR_MESSAGE);
                paidAmount.requestFocus();
                return;
            }
        }
        
        String customerName = customer.getSelectedItem().toString();
        
        if(customerName.equalsIgnoreCase("--select--"))
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please select a Customer"), "Error Message", JOptionPane.ERROR_MESSAGE);
            customer.requestFocus();
            return;
        }
        
        if(customerName.equalsIgnoreCase("add new"))
        {
            if(newCustomer.getText().trim().isEmpty())
            {
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please enter the Customer name"), "Error Message", JOptionPane.ERROR_MESSAGE);
                newCustomer.requestFocus();
                return;
            }
            
            customerName = newCustomer.getText().trim();
            
            customerMaster.setName(customerName);
            
            List<CustomerMaster> customerList = customerMasterQuery.getCustomer(customerMaster);
            if(!(customerList.isEmpty()))
            {
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("This Customer name already exists"), "Error Message", JOptionPane.ERROR_MESSAGE);
                newCustomer.requestFocus();
                return;
            }
        }
        
        int confirm = JOptionPane.showConfirmDialog(null, MessageFormat.getMessage("Are you sure of saving these details?"));
        if(confirm == JOptionPane.YES_OPTION)
        {
            customerMaster.setName(customerName);
            customerMaster.setContact(contact.getText().trim());
            customerMaster.setAddress(address.getText().trim());
            customerMaster.setGstNumber(gstNumber.getText().trim());
            
            List<CustomerMaster> customerList = customerMasterQuery.getCustomer(customerMaster);

            if(customerList.isEmpty())
            {
                customerMaster.setBalance(new BigDecimal(0));
                customerMasterQuery.insertIntoCustomerMaster(customerMaster);
            }
            else
            {
                for(CustomerMaster cm: customerList)
                {
                   customerMaster.setId(cm.getId());
                   customerMaster.setBalance(cm.getBalance());
                }

                customerMasterQuery.updateCustomerMaster(customerMaster);
            }
            
            String paymentMode = this.paymentMode.getText();
            
            SaleMaster saleMaster = new SaleMaster();
            SaleMasterQuery saleMasterQuery = new SaleMasterQuery();
            
            CustomerPartialPayment customerPartialPayment = new CustomerPartialPayment();
            CustomerPartialPaymentQuery customerPartialPaymentQuery = new CustomerPartialPaymentQuery();
            
            customerPartialPayment.setPaymentMode(paymentMode);
            customerPartialPayment.setBank(bank.getText());
            customerPartialPayment.setChequeOrCardNumber(number.getText());
            customerPartialPayment.setCustomerMaster(customerMaster);
            customerPartialPayment.setDate(saleDate.getDate());
            
            if(!(paymentMode.equalsIgnoreCase("cheque")))
                customerPartialPayment.setStatus("1");
            else
                customerPartialPayment.setStatus("0");
            customerPartialPayment.setPaidAmount(new BigDecimal(paidAmount.getText().trim()));
            
            if(chequeDate.getDate() != null)
                customerPartialPayment.setChequeDate(chequeDate.getDate());
            
            saleMaster.setDiscount(new BigDecimal(discount.getText().trim()));
            saleMaster.setFinalBillAmount(new BigDecimal(finalAmount.getText().trim()));
            saleMaster.setBillAmount(new BigDecimal(billAmount.getText()));
            saleMaster.setId(Integer.parseInt(billId.getText()));
            saleMaster.setCustomerMaster(customerMaster);
            saleMaster.setStatus("1");
            saleMaster.setReference(reference.getText().trim());
            
            if(remark.getText().equalsIgnoreCase("gst taken"))
                saleMaster.setRemark("GST Taken");
            else
                saleMaster.setRemark("GST Not Taken");
            saleMasterQuery.updateSaleMaster(saleMaster);
                
            customerPartialPaymentQuery.insertIntoCustomerPartialPayment(customerPartialPayment);
            
            if(paymentMode.equalsIgnoreCase("cheque"))
              customerMaster.setBalance(customerMaster.getBalance().add(new BigDecimal(finalAmount.getText())));
            else
                customerMaster.setBalance((customerMaster.getBalance().add(new BigDecimal(finalAmount.getText()))).subtract(new BigDecimal(paidAmount.getText())));
            
            customerMasterQuery.updateCustomerBalance(customerMaster);
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Sale successful"));
            String remark = this.remark.getText().trim();
            
            dispose();
            
            SalesPageView storeDetails = new SalesPageView(jDesktopPane);
            storeDetails.setTitle("Sales Page");
            jDesktopPane.add(storeDetails);
            SetDimension setDimension = new SetDimension();
            setDimension.setInternalFrameLocation(jDesktopPane, storeDetails);
            storeDetails.setVisible(true);
            
            if(remark.equalsIgnoreCase("gst taken"))
                printBill(saleMaster, true);
            else
                printBill(saleMaster, false);
        }   
    }
    
    private void printBill(SaleMaster saleMaster, boolean flag) 
    {
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;
        
        String joinQuery =  "SELECT\n" +
                            "     counter.`Id` AS counter_Id,\n" +
                            "     counter.`name` AS counter_name,\n" +
                            "     counter.`status` AS counter_status,\n" +
                            "     item_master.`Id` AS item_master_Id,\n" +
                            "     item_master.`name` AS item_master_name,\n" +
                            "     item_master.`unitPrice` AS item_master_unitPrice,\n" +
                            "     item_master.`gstPercent` AS item_master_gstPercent,\n" +
                            "     item_master.`sellingPrice` AS item_master_sellingPrice,\n" +
                            "     item_master.`sellingGstPercent` AS item_master_sellingGstPercent,\n" +
                            "     item_master.`finalSellingPrice` AS item_master_finalSellingPrice,\n" +
                            "     item_master.`hsnCode` AS hsnCode,\n" +
                            "     sale_details.`Id` AS sale_details_Id,\n" +
                            "     sale_details.`saleId` AS sale_details_saleId,\n" +
                            "     sale_details.`itemId` AS sale_details_itemId,\n" +
                            "     sale_details.`unitPrice` AS sale_details_unitPrice,\n" +
                            "     sale_details.`gstPercent` AS sale_details_gstPercent,\n" +
                            "     sale_details.`sellingPrice` AS sale_details_sellingPrice,\n" +
                            "     sale_details.`quantity` AS sale_details_quantity,\n" +
                            "     sale_details.`total` AS sale_details_total,\n" +
                            "     sale_master.`Id` AS sale_master_Id,\n" +
                            "     sale_master.`date` AS sale_master_date,\n" +
                            "     sale_master.`storeId` AS sale_master_storeId,\n" +
                            "     sale_master.`counterId` AS sale_master_counterId,\n" +
                            "     sale_master.`customerId` AS sale_master_customerId,\n" +
                            "     sale_master.`billAmount` AS sale_master_billAmount,\n" +
                            "     sale_master.`discount` AS sale_master_discount,\n" +
                            "     sale_master.`finalBillAmount` AS sale_master_finalBillAmount,\n" +
                            "     sale_master.`status` AS sale_master_status,\n" +
                            "     sale_master.`remark` AS sale_master_remark,\n" +
                            "     store_details.`Id` AS store_details_Id,\n" +
                            "     store_details.`name` AS store_details_name,\n" +
                            "     store_details.`address` AS store_details_address,\n" +
                            "     store_details.`city` AS store_details_city,\n" +
                            "     store_details.`state` AS store_details_state,\n" +
                            "     store_details.`pincode` AS store_details_pincode,\n" +
                            "     store_details.`phone` AS store_details_phone,\n" +
                            "     store_details.`website` AS store_details_website,\n" +
                            "     store_details.`email` AS store_details_email,\n" +
                            "     store_details.`gstNumber` AS store_details_gstNumber,\n" +
                            "     store_details.`photo` AS store_details_photo\n" +
                            "FROM\n" +
                            "     `item_master` item_master INNER JOIN `sale_details` sale_details ON item_master.`Id` = sale_details.`itemId`\n" +
                            "     INNER JOIN `sale_master` sale_master ON sale_details.`saleId` = sale_master.`Id`\n" +
                            "     INNER JOIN `counter` counter ON sale_master.`counterId` = counter.`Id`\n" +
                            "     INNER JOIN `store_details` store_details ON sale_master.`storeId` = store_details.`Id` \n" +
                            "WHERE sale_master.id = " + saleMaster.getId();
        
        try
        {
            connection = MyConnection.createConnection();
            statement = connection.createStatement();
            resultSet = statement.executeQuery(joinQuery);
            
            String reportSource = "";
            
            if(flag)
               reportSource = ReadFile.getPath() + "Reports\\GstSaleDetails.jrxml"; 
            else
                reportSource = ReadFile.getPath() + "Reports\\NonGstSaleDetails.jrxml"; 
            
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JRResultSetDataSource resultSetDataSource = new JRResultSetDataSource(resultSet);
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, resultSetDataSource);
            JasperViewer.viewReport(jasperPrint, false);
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        finally
        {
            if (resultSet != null) 
            {
                try 
                {
                //    System.out.println("Statement");
                    resultSet.close();
                } 
                catch (SQLException e) 
                { /* ignored */}
            }
            if (statement != null) 
            {
                try 
                {
                //    System.out.println("Statement");
                    statement.close();
                } 
                catch (SQLException e) 
                { /* ignored */}
            }
            
            if (connection != null) 
            {
                try 
                {
                //    System.out.println("Connection");
                    connection.close();
                } 
                catch (SQLException e)
                {

                }
            }
        }
    }
}
