/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EOD.java
 *
 * Created on Apr 2, 2016, 2:41:26 PM
 */

package com.grocery.view;


import com.grocery.bean.BeginningCash;
import com.grocery.bean.CustomerPartialPayment;
import com.grocery.query.BeginningCashQuery;
import com.grocery.query.CustomerPartialPaymentQuery;
import com.grocery.query.ExpensesQuery;
import com.grocery.read.MessageFormat;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;


/**
 *
 * @author comp
 */
public class EOD extends javax.swing.JInternalFrame implements ActionListener{
Calendar calendar = Calendar.getInstance();
private int hour, minute, second;
int id;
Date date = new Date();
private BigDecimal beginningCash;
private BigDecimal expenses;
private JTextFieldDateEditor editor;

    /** Creates new form EOD */
    public EOD() {
        initComponents();
        new Timer(1000, this).start();
        
        currentDate.setDate(date);
        editor = (JTextFieldDateEditor)currentDate.getDateEditor();
        editor.setEditable(false);
        currentDate.setMinSelectableDate(date);
        
        loadBeginningCash();
        loadExpenses();
        loadCash();
        
        getAmountReceived(currentDate.getDate(),"PayTM", paytm);
        getAmountReceived(currentDate.getDate(),"Cash", cash);
        getAmountReceived(currentDate.getDate(),"Card", card);

      //  jMenu.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        curtime = new javax.swing.JLabel();
        currentDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        availableCash = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        twoThousand = new javax.swing.JTextField();
        fivehred = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hundred = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fifty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        twenty = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ten = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        five = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        two = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        one = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        c1 = new javax.swing.JFormattedTextField();
        c2 = new javax.swing.JFormattedTextField();
        c3 = new javax.swing.JFormattedTextField();
        c4 = new javax.swing.JFormattedTextField();
        c5 = new javax.swing.JFormattedTextField();
        c6 = new javax.swing.JFormattedTextField();
        c7 = new javax.swing.JFormattedTextField();
        c8 = new javax.swing.JFormattedTextField();
        c9 = new javax.swing.JFormattedTextField();
        save = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        c10 = new javax.swing.JFormattedTextField();
        twoHundred = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        card = new javax.swing.JTextField();
        cash = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        paytm = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("End Of Day");

        curtime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        curtime.setForeground(new java.awt.Color(255, 255, 255));

        currentDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        currentDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                currentDatePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(currentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(curtime, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(currentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(curtime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Beginning Cash:");

        availableCash.setEditable(false);
        availableCash.setBackground(new java.awt.Color(255, 255, 153));
        availableCash.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        availableCash.setForeground(new java.awt.Color(255, 0, 0));
        availableCash.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Count");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Amount");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("2000");

        twoThousand.setEditable(false);
        twoThousand.setBackground(new java.awt.Color(255, 255, 153));
        twoThousand.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        twoThousand.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        twoThousand.setText("0");
        twoThousand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoThousandActionPerformed(evt);
            }
        });

        fivehred.setEditable(false);
        fivehred.setBackground(new java.awt.Color(255, 255, 153));
        fivehred.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fivehred.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        fivehred.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("500");

        hundred.setEditable(false);
        hundred.setBackground(new java.awt.Color(255, 255, 153));
        hundred.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hundred.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        hundred.setText("0");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("100");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("50");

        fifty.setEditable(false);
        fifty.setBackground(new java.awt.Color(255, 255, 153));
        fifty.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        fifty.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        fifty.setText("0");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("20");

        twenty.setEditable(false);
        twenty.setBackground(new java.awt.Color(255, 255, 153));
        twenty.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        twenty.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        twenty.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("10");

        ten.setEditable(false);
        ten.setBackground(new java.awt.Color(255, 255, 153));
        ten.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ten.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ten.setText("0");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("5");

        five.setEditable(false);
        five.setBackground(new java.awt.Color(255, 255, 153));
        five.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        five.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        five.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("2");

        two.setEditable(false);
        two.setBackground(new java.awt.Color(255, 255, 153));
        two.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        two.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        two.setText("0");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("1");

        one.setEditable(false);
        one.setBackground(new java.awt.Color(255, 255, 153));
        one.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        one.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        one.setText("0");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Total ");

        subtotal.setEditable(false);
        subtotal.setBackground(new java.awt.Color(255, 255, 153));
        subtotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subtotal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        c1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c1FocusLost(evt);
            }
        });
        c1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c1KeyTyped(evt);
            }
        });

        c2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c2FocusLost(evt);
            }
        });
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        c2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c2KeyTyped(evt);
            }
        });

        c3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c3FocusLost(evt);
            }
        });
        c3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c3KeyTyped(evt);
            }
        });

        c4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c4FocusLost(evt);
            }
        });
        c4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c4KeyTyped(evt);
            }
        });

        c5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c5FocusLost(evt);
            }
        });
        c5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c5KeyTyped(evt);
            }
        });

        c6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c6FocusLost(evt);
            }
        });
        c6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c6KeyTyped(evt);
            }
        });

        c7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c7FocusLost(evt);
            }
        });
        c7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c7KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c7KeyTyped(evt);
            }
        });

        c8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c8FocusLost(evt);
            }
        });
        c8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c8KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c8KeyTyped(evt);
            }
        });

        c9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c9FocusLost(evt);
            }
        });
        c9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c9KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c9KeyTyped(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save.setText("Save");
        save.setMnemonic(KeyEvent.VK_S);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("200");

        c10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        c10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                c10FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                c10FocusLost(evt);
            }
        });
        c10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c10KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c10KeyTyped(evt);
            }
        });

        twoHundred.setEditable(false);
        twoHundred.setBackground(new java.awt.Color(255, 255, 153));
        twoHundred.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        twoHundred.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        twoHundred.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtotal))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(twenty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c4, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(c1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(c3)
                                            .addComponent(c2))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hundred)
                                    .addComponent(fifty)
                                    .addComponent(fivehred)
                                    .addComponent(twoThousand)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(twoHundred, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(five))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(one)))
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(twoThousand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(fivehred)))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twoHundred)
                    .addComponent(jLabel18)
                    .addComponent(c10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hundred)
                    .addComponent(jLabel7)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fifty)
                    .addComponent(jLabel8)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twenty)
                    .addComponent(jLabel9)
                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ten)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(five)
                    .addComponent(jLabel11)
                    .addComponent(c7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(two)
                    .addComponent(c8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(availableCash, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(availableCash, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Amount received by CARD:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Amount received in CASH:");

        card.setEditable(false);
        card.setBackground(new java.awt.Color(255, 255, 153));
        card.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        card.setForeground(new java.awt.Color(255, 0, 0));
        card.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cash.setEditable(false);
        cash.setBackground(new java.awt.Color(255, 255, 153));
        cash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cash.setForeground(new java.awt.Color(255, 0, 0));
        cash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Amount received by Paytm:");

        paytm.setEditable(false);
        paytm.setBackground(new java.awt.Color(255, 255, 153));
        paytm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paytm.setForeground(new java.awt.Color(255, 0, 0));
        paytm.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paytm, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(paytm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twoThousandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoThousandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoThousandActionPerformed

    private void c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusLost
        // TODO add your handling code here:
         if(c1.getText().equals(""))
        {
            c1.setText("0");
        }
    }//GEN-LAST:event_c1FocusLost

    private void c1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c1FocusGained
        // TODO add your handling code here:
        // c1.setText("");
    }//GEN-LAST:event_c1FocusGained

    private void c1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyReleased
        // TODO add your handling code here:
        if(c1.getText().equals(""))
        {
            twoThousand.setText("0");
        }
        else
        {
            int count=Integer.parseInt(c1.getText());
            int t=count*2000;
            twoThousand.setText(String.valueOf(t));
        }
        getTotal();
    }//GEN-LAST:event_c1KeyReleased

    private void c2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c2FocusGained
        // TODO add your handling code here:
        //c2.setText("");
    }//GEN-LAST:event_c2FocusGained

    private void c2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c2FocusLost
        // TODO add your handling code here:
        if(c2.getText().equals(""))
        {
            c2.setText("0");
        }
    }//GEN-LAST:event_c2FocusLost

    private void c2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c2KeyReleased
        // TODO add your handling code here:
        if(c2.getText().equals(""))
        {
            fivehred.setText("0");
        }
        else{
        int count=Integer.parseInt(c2.getText());
        int t=count*500;
        fivehred.setText(String.valueOf(t));
        }
        getTotal();
    }//GEN-LAST:event_c2KeyReleased

    private void c3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c3FocusGained
        // TODO add your handling code here:
        //c3.setText("");
    }//GEN-LAST:event_c3FocusGained

    private void c3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c3FocusLost
        // TODO add your handling code here:
        if(c3.getText().equals(""))
        {
            c3.setText("0");
        }
    }//GEN-LAST:event_c3FocusLost

    private void c3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c3KeyReleased
        // TODO add your handling code here:
        if(c3.getText().equals(""))
        {
            hundred.setText("0");
        }
        else{
        int count=Integer.parseInt(c3.getText());
        int t=count*100;
        hundred.setText(String.valueOf(t));
        }
        getTotal();
    }//GEN-LAST:event_c3KeyReleased

    private void c4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c4FocusGained
        // TODO add your handling code here:
        //c4.setText("");
    }//GEN-LAST:event_c4FocusGained

    private void c4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c4FocusLost
        // TODO add your handling code here:
        if(c4.getText().equals(""))
        {
            c4.setText("0");
        }
    }//GEN-LAST:event_c4FocusLost

    private void c4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c4KeyReleased
        // TODO add your handling code here:
         if(c4.getText().equals(""))
        {
            fifty.setText("0");
        }
        else{
        int count=Integer.parseInt(c4.getText());
        int t=count*50;
        fifty.setText(String.valueOf(t));
        }
        getTotal(); 
    }//GEN-LAST:event_c4KeyReleased

    private void c5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c5FocusGained
        // TODO add your handling code here:
          //c5.setText("");
    }//GEN-LAST:event_c5FocusGained

    private void c5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c5FocusLost
        // TODO add your handling code here:
        if(c5.getText().equals(""))
        {
            c5.setText("0");
        }
    }//GEN-LAST:event_c5FocusLost

    private void c5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c5KeyReleased
        if(c5.getText().equals(""))
        {
            twenty.setText("0");
        }
        else{
        int count=Integer.parseInt(c5.getText());
        int t=count*20;
        twenty.setText(String.valueOf(t));
        }
        getTotal();
    }//GEN-LAST:event_c5KeyReleased

    private void c6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c6FocusGained
        
    }//GEN-LAST:event_c6FocusGained

    private void c6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c6FocusLost
        // TODO add your handling code here:
         if(c6.getText().equals(""))
        {
            c6.setText("0");
        }
    }//GEN-LAST:event_c6FocusLost

    private void c6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c6KeyReleased
        // TODO add your handling code here:
        if(c6.getText().equals(""))
        {
            ten.setText("0");
        }
        else{
        int count=Integer.parseInt(c6.getText());
        int t=count*10;
        ten.setText(String.valueOf(t));
        }
        getTotal();
    }//GEN-LAST:event_c6KeyReleased

    private void c7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c7FocusGained
        // TODO add your handling code here:
        //c7.setText("");
    }//GEN-LAST:event_c7FocusGained

    private void c7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c7FocusLost
        // TODO add your handling code here:
        if(c7.getText().equals(""))
        {
            c7.setText("0");
        }
    }//GEN-LAST:event_c7FocusLost

    private void c7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c7KeyReleased
        // TODO add your handling code here:
         if(c7.getText().equals(""))
        {
            five.setText("0");
        }
        else
        {
            int count=Integer.parseInt(c7.getText());
            int t=count*5;
            five.setText(String.valueOf(t));
        }
        getTotal();
    }//GEN-LAST:event_c7KeyReleased

    private void c8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c8FocusGained
        // TODO add your handling code here:
        //c8.setText("");
    }//GEN-LAST:event_c8FocusGained

    private void c8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c8FocusLost
        // TODO add your handling code here:
        if(c8.getText().equals(""))
        {
            c8.setText("0");
        }
    }//GEN-LAST:event_c8FocusLost

    private void c8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c8KeyReleased
        // TODO add your handling code here:
        if(c8.getText().equals(""))
        {
            two.setText("0");
        }
        else{
        int count=Integer.parseInt(c8.getText());
        int t=count*2;
        two.setText(String.valueOf(t));
        }
        getTotal();
    }//GEN-LAST:event_c8KeyReleased

    private void c9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c9FocusGained
        // TODO add your handling code here:
         //c9.setText("");
    }//GEN-LAST:event_c9FocusGained

    private void c9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c9FocusLost
        // TODO add your handling code here:
        if(c9.getText().equals(""))
        {
            c9.setText("0");
        }
    }//GEN-LAST:event_c9FocusLost

    private void c9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c9KeyReleased
        // TODO add your handling code here:
        if(c9.getText().equals(""))
        {
            one.setText("0");
        }
        else{
        int count=Integer.parseInt(c9.getText());
        int t=count*1;
        one.setText(String.valueOf(t));
        }
        getTotal();
    }//GEN-LAST:event_c9KeyReleased

    private void c1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c1KeyTyped

    private void c2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c2KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c2KeyTyped

    private void c3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c3KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c3KeyTyped

    private void c4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c4KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c4KeyTyped

    private void c5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c5KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c5KeyTyped

    private void c6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c6KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c6KeyTyped

    private void c7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c7KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c7KeyTyped

    private void c8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c8KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c8KeyTyped

    private void c9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c9KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c9KeyTyped

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        save();
    }//GEN-LAST:event_saveActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashActionPerformed

    private void currentDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_currentDatePropertyChange
        try
        {
            getAmountReceived(currentDate.getDate(),"PayTM", paytm);
            getAmountReceived(currentDate.getDate(),"Cash", cash);
            getAmountReceived(currentDate.getDate(),"Card", card);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_currentDatePropertyChange

    private void saveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            save();
    }//GEN-LAST:event_saveKeyPressed

    private void c10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c10FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_c10FocusGained

    private void c10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_c10FocusLost
        if(c10.getText().trim().isEmpty())
            c10.setText("0");
    }//GEN-LAST:event_c10FocusLost

    private void c10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c10KeyReleased
        if(c10.getText().equals(""))
        {
            twoHundred.setText("0");
        }
        else{
        int count=Integer.parseInt(c10.getText());
        int t=count*200;
        twoHundred.setText(String.valueOf(t));
        }
        getTotal();
    }//GEN-LAST:event_c10KeyReleased

    private void c10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c10KeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_c10KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availableCash;
    private javax.swing.JFormattedTextField c1;
    private javax.swing.JFormattedTextField c10;
    private javax.swing.JFormattedTextField c2;
    private javax.swing.JFormattedTextField c3;
    private javax.swing.JFormattedTextField c4;
    private javax.swing.JFormattedTextField c5;
    private javax.swing.JFormattedTextField c6;
    private javax.swing.JFormattedTextField c7;
    private javax.swing.JFormattedTextField c8;
    private javax.swing.JFormattedTextField c9;
    private javax.swing.JTextField card;
    private javax.swing.JTextField cash;
    private com.toedter.calendar.JDateChooser currentDate;
    private javax.swing.JLabel curtime;
    private javax.swing.JTextField fifty;
    private javax.swing.JTextField five;
    private javax.swing.JTextField fivehred;
    private javax.swing.JTextField hundred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField one;
    private javax.swing.JTextField paytm;
    private javax.swing.JButton save;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField ten;
    private javax.swing.JTextField twenty;
    private javax.swing.JTextField two;
    private javax.swing.JTextField twoHundred;
    private javax.swing.JTextField twoThousand;
    // End of variables declaration//GEN-END:variables

private void updateTime() {

        calendar.setTimeInMillis( System.currentTimeMillis() ); //Update the calendar's time

        hour = calendar.get( 11 ); //Calendar field 11 is hours

        minute = calendar.get( 12 ); //Field 12
      second = calendar.get( 13 ); //Field 13

    }
  @Override
    public void actionPerformed(ActionEvent e) {
         updateTime(); //Update time
         String formattedString = String.format("%02d:%02d:%02d", hour, minute, second);
         curtime.setText(formattedString); //Update label text

        repaint(); //Update gui//To change body of generated methods, choose Tools | Templates.


    }

    private void clear() 
    {
        c1.setText("");
        c2.setText("");
        c3.setText("");
        c4.setText("");
        c5.setText("");
        c6.setText("");
        c7.setText("");
        c8.setText("");
        c9.setText("");
        c10.setText("");
        
        twoThousand.setText("0");
        fivehred.setText("0");
        hundred.setText("0");
        fifty.setText("0");
        twenty.setText("0");
        ten.setText("0");
        five.setText("0");
        two.setText("0");
        one.setText("0");
        twoHundred.setText("0");
        
        subtotal.setText("");
        
    }
    
    private void getAmountReceived(Date date, String paymentMode, JTextField textField) 
    {
        CustomerPartialPayment customerPartialPayment = new CustomerPartialPayment();
        
        customerPartialPayment.setDate(date);
        customerPartialPayment.setTo(date);
        customerPartialPayment.setPaymentMode(paymentMode);
        
        CustomerPartialPaymentQuery customerPartialPaymentQuery = new CustomerPartialPaymentQuery();
        
        List<BigDecimal> list = customerPartialPaymentQuery.getTotal(customerPartialPayment);
        
        for(BigDecimal bd: list)
        {
            if(bd == null)
                textField.setText("0.00");
            else
                textField.setText(String.valueOf(bd));
        }
    }

    private void save() 
    {
        BeginningCash beginningCash = new BeginningCash();
        beginningCash.setDate(currentDate.getDate());
        
        BeginningCashQuery beginningCashQuery = new BeginningCashQuery();
        
        List<BeginningCash> list = beginningCashQuery.checkEntry(beginningCash);
        
        if(list.isEmpty())
        {
            if(subtotal.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please enter the number of notes/coins"), "Error Message", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
            
            Date date = new Date();
            Date currentDate = this.currentDate.getDate();
            
            String stringDate = dateFormat.format(date);
            String stringCurrentDate = dateFormat.format(currentDate);
            
            try
            {
                date = dateFormat.parse(stringDate);
                currentDate = dateFormat.parse(stringCurrentDate);

                if(currentDate.compareTo(date) > 0)
                {
                    JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Saving Failed!!!\nChosen Date is after Current Date"),"Error Message", JOptionPane.ERROR_MESSAGE);
                    return;
                }


                float amount = 0;
                float saleAmount = 0;

                int confirm = JOptionPane.showConfirmDialog(null, MessageFormat.getMessage("Are you sure of saving this detail?"));
                if(confirm == JOptionPane.YES_OPTION)
                {
                    amount = Float.parseFloat(subtotal.getText());
                    saleAmount = Float.parseFloat(cash.getText());

                    if(amount < saleAmount)
                    {
                        JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Saving Failed!!!\nAmount entered is less than Amount Received"), "Error Message", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    
                    beginningCash.setDate(currentDate);
                    beginningCash.setAmount(new BigDecimal(subtotal.getText()));
                    
                    beginningCashQuery.insertIntoBeginningCash(beginningCash);
                    JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Amount added successfully"));
                    loadBeginningCash();
                    loadExpenses();
                    loadCash();
                    clear();
                }
                
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Saving failed.\n Entry for this date is already done"), "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadBeginningCash() 
    {
        BeginningCashQuery beginningCashQuery = new BeginningCashQuery();
        
        List<BigDecimal> list = beginningCashQuery.getBeginningCash();
        
        for(BigDecimal bd: list)
            beginningCash = bd;
    }

    private void loadExpenses() 
    {
        ExpensesQuery expensesQuery = new ExpensesQuery();
        
        List<BigDecimal> list = expensesQuery.getExpenses();
        
        for(BigDecimal bd: list)
            expenses = bd;
    }

    private void loadCash() 
    {
        availableCash.setText(String.valueOf(beginningCash.subtract(expenses)));
    }
    
    public void getTotal()
    {
        try
        {
            int total=0;
            int values[]={0,0,0,0,0,0,0,0,0,0};
            values[0]=Integer.parseInt(twoThousand.getText());
            values[1]=Integer.parseInt(fivehred.getText());
            values[2]=Integer.parseInt(hundred.getText());
            values[3]=Integer.parseInt(fifty.getText());
            values[4]=Integer.parseInt(twenty.getText());
            values[5]=Integer.parseInt(ten.getText());
            values[6]=Integer.parseInt(five.getText());
            values[7]=Integer.parseInt(two.getText());
            values[8]=Integer.parseInt(one.getText());
            values[9] = Integer.parseInt(twoHundred.getText());

            for(int i=0;i<values.length;i++)
            {
                total=total+values[i];
            }
            subtotal.setText(""+total);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please enter numeric values only"), "Error message", JOptionPane.ERROR_MESSAGE);
        }
    }
}
