/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.view;

import com.grocery.bean.CustomerMaster;
import com.grocery.bean.SaleMaster;
import com.grocery.bean.VendorBillMaster;
import com.grocery.bean.VendorMaster;
import com.grocery.dimension.SetDimension;
import com.grocery.query.CustomerMasterQuery;
import com.grocery.query.SaleMasterQuery;
import com.grocery.query.VendorBillMasterQuery;
import com.grocery.query.VendorQuery;
import com.grocery.read.MessageFormat;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Admin
 */
public class PurchaseReturnView extends javax.swing.JInternalFrame {

    private Date currentDate = new Date();
    private JDesktopPane jDesktopPane;
    private JTextFieldDateEditor editor;
    private boolean flag;

    public PurchaseReturnView(JDesktopPane jDesktopPane, boolean flag) 
    {
        initComponents();
        this.flag = flag;
        
        this.jDesktopPane = jDesktopPane;
        editor = (JTextFieldDateEditor)from.getDateEditor();
        editor.setEditable(false);
        
        editor = (JTextFieldDateEditor)to.getDateEditor();
        editor.setEditable(false);
        
        from.setDate(currentDate);
        to.setDate(currentDate);
        
        billId.setSelected(true);
        jPanelBillId.setVisible(true);
        jPanelChallan.setVisible(false);
        jPanelDate.setVisible(false);
        jPanelVendor.setVisible(false);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        
        
        jTable1.getTableHeader().setFont(new Font("Georgia", Font.BOLD, 11));
        
        if(flag)
        {
           challan.setVisible(true);
            loadVendor();
        }
        else
        {
            challan.setVisible(false);
            jLabelPurchase.setText("Sales Return");
            name.setText("Customer Name");
            jLabelName.setText("Customer");
            JTableHeader header= jTable1.getTableHeader();
            TableColumnModel colMod = header.getColumnModel();
            TableColumn tabCol = colMod.getColumn(3);
            tabCol.setHeaderValue("Customer Name");
            
            colMod = header.getColumnModel();
            tabCol = colMod.getColumn(2);
            tabCol.setHeaderValue("Sales Date");
            
            jTable1.getColumnModel().getColumn(5).setMinWidth(0);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(0);
            
            loadCustomer();
        }
              
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        billId = new javax.swing.JRadioButton();
        challan = new javax.swing.JRadioButton();
        name = new javax.swing.JRadioButton();
        date = new javax.swing.JRadioButton();
        jPanelBillId = new javax.swing.JPanel();
        txtBillId = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanelChallan = new javax.swing.JPanel();
        txtChallan = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jPanelVendor = new javax.swing.JPanel();
        vendorName = new javax.swing.JComboBox<>();
        jLabelName = new javax.swing.JLabel();
        jPanelDate = new javax.swing.JPanel();
        from = new com.toedter.calendar.JDateChooser();
        to = new com.toedter.calendar.JDateChooser();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        details = new javax.swing.JButton();
        jLabelPurchase = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel40.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Search By:");

        buttonGroup1.add(billId);
        billId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        billId.setText("Bill Id");
        billId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billIdActionPerformed(evt);
            }
        });

        buttonGroup1.add(challan);
        challan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        challan.setText("Challan #");
        challan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                challanActionPerformed(evt);
            }
        });

        buttonGroup1.add(name);
        name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name.setText("Vendor Name:");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        buttonGroup1.add(date);
        date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        date.setText("Date");
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        jPanelBillId.setBackground(new java.awt.Color(255, 255, 255));

        txtBillId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtBillId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBillId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBillIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBillIdKeyTyped(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel43.setText("Bill Id:");

        javax.swing.GroupLayout jPanelBillIdLayout = new javax.swing.GroupLayout(jPanelBillId);
        jPanelBillId.setLayout(jPanelBillIdLayout);
        jPanelBillIdLayout.setHorizontalGroup(
            jPanelBillIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillIdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBillId, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanelBillIdLayout.setVerticalGroup(
            jPanelBillIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBillIdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtBillId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelChallan.setBackground(new java.awt.Color(255, 255, 255));

        txtChallan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtChallan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChallan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChallanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtChallanKeyTyped(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel44.setText("Challan #:");

        javax.swing.GroupLayout jPanelChallanLayout = new javax.swing.GroupLayout(jPanelChallan);
        jPanelChallan.setLayout(jPanelChallanLayout);
        jPanelChallanLayout.setHorizontalGroup(
            jPanelChallanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChallanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtChallan, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelChallanLayout.setVerticalGroup(
            jPanelChallanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelChallanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtChallan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelVendor.setBackground(new java.awt.Color(255, 255, 255));

        vendorName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vendorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendorNameActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelName.setText("Vendor:");

        javax.swing.GroupLayout jPanelVendorLayout = new javax.swing.GroupLayout(jPanelVendor);
        jPanelVendor.setLayout(jPanelVendorLayout);
        jPanelVendorLayout.setHorizontalGroup(
            jPanelVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendorName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVendorLayout.setVerticalGroup(
            jPanelVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelVendorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelDate.setBackground(new java.awt.Color(255, 255, 255));

        from.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        from.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fromPropertyChange(evt);
            }
        });

        to.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        to.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                toPropertyChange(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("From:");

        jLabel42.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("To:");

        javax.swing.GroupLayout jPanelDateLayout = new javax.swing.GroupLayout(jPanelDate);
        jPanelDate.setLayout(jPanelDateLayout);
        jPanelDateLayout.setHorizontalGroup(
            jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDateLayout.createSequentialGroup()
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelDateLayout.setVerticalGroup(
            jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(from, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(to, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendor Id", "Bill Id", "Purchase Date", "Vendor Name", "Reference", "Challan #", "Bill Amount", "Discount", "Final Bill Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        details.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        details.setText("Bill Details");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });

        jLabelPurchase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPurchase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPurchase.setText("Purchase Return");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanelBillId, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(billId)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelChallan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(challan)
                        .addGap(95, 95, 95)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(name)
                        .addGap(188, 188, 188)
                        .addComponent(date)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelVendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(details)
                .addGap(502, 502, 502))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(billId)
                        .addComponent(challan)
                        .addComponent(name)
                        .addComponent(date))
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelBillId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelChallan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelVendor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(details)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChallanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChallanKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c == KeyEvent.VK_DELETE || Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_txtChallanKeyTyped

    private void txtBillIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBillIdKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)))
            evt.consume();
    }//GEN-LAST:event_txtBillIdKeyTyped

    private void billIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billIdActionPerformed
        if(billId.isSelected())
        {
            DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
            defaultTableModel.setRowCount(0);
            txtBillId.setText("");
            jPanelBillId.setVisible(true);
            jPanelChallan.setVisible(false);
            jPanelDate.setVisible(false);
            jPanelVendor.setVisible(false);
        }
    }//GEN-LAST:event_billIdActionPerformed

    private void challanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_challanActionPerformed
        if(challan.isSelected())
        {
            DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
            defaultTableModel.setRowCount(0);
            txtChallan.setText("");
            jPanelBillId.setVisible(false);
            jPanelChallan.setVisible(true);
            jPanelDate.setVisible(false);
            jPanelVendor.setVisible(false);
        }
    }//GEN-LAST:event_challanActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        if(name.isSelected())
        {
            DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
            defaultTableModel.setRowCount(0);
            jPanelBillId.setVisible(false);
            jPanelChallan.setVisible(false);
            jPanelDate.setVisible(false);
            jPanelVendor.setVisible(true);
        }
    }//GEN-LAST:event_nameActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        if(date.isSelected())
        {
            DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
            defaultTableModel.setRowCount(0);
            from.setDate(currentDate);
            to.setDate(currentDate);
            jPanelBillId.setVisible(false);
            jPanelChallan.setVisible(false);
            jPanelDate.setVisible(true);
            jPanelVendor.setVisible(false);
        }
    }//GEN-LAST:event_dateActionPerformed

    private void txtBillIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBillIdKeyReleased
        DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
        defaultTableModel.setRowCount(0);
        
        if(!(txtBillId.getText().trim().isEmpty()))
            loadTable(txtBillId.getText().trim(), "Bill Id");
    }//GEN-LAST:event_txtBillIdKeyReleased

    private void txtChallanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChallanKeyReleased
        DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
        defaultTableModel.setRowCount(0);
        
        if(!(txtChallan.getText().trim().isEmpty()))
            loadTable(txtChallan.getText().trim(), "challan");
    }//GEN-LAST:event_txtChallanKeyReleased

    private void vendorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendorNameActionPerformed
        if(jPanelVendor.isVisible())
        {
            if(vendorName.getItemCount() > 0)
                loadTable(vendorName.getSelectedItem().toString(), "vendor");  
        }
    }//GEN-LAST:event_vendorNameActionPerformed

    private void fromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fromPropertyChange
        if(jPanelDate.isVisible())
        {
            DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
            defaultTableModel.setRowCount(0);
            
            if(from.getDate() != null)
                loadTable(null, "date");
        }
    }//GEN-LAST:event_fromPropertyChange

    private void toPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_toPropertyChange
        if(jPanelDate.isVisible())
        {
            DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
            defaultTableModel.setRowCount(0);
            
            if(to.getDate() != null)
                loadTable(null, "date");
        }
    }//GEN-LAST:event_toPropertyChange

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
        billDetails();
    }//GEN-LAST:event_detailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton billId;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton challan;
    private javax.swing.JRadioButton date;
    private javax.swing.JButton details;
    private com.toedter.calendar.JDateChooser from;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPurchase;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBillId;
    private javax.swing.JPanel jPanelChallan;
    private javax.swing.JPanel jPanelDate;
    private javax.swing.JPanel jPanelVendor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton name;
    private com.toedter.calendar.JDateChooser to;
    private javax.swing.JTextField txtBillId;
    private javax.swing.JTextField txtChallan;
    private javax.swing.JComboBox<String> vendorName;
    // End of variables declaration//GEN-END:variables

    private void loadVendor() 
    {
        VendorMaster vendorMaster = new VendorMaster();
        VendorQuery vendorQuery = new VendorQuery();
        
        DefaultComboBoxModel defaultComboBoxModel = (DefaultComboBoxModel)vendorName.getModel();
            
        List<VendorMaster> list = vendorQuery.getVendorDetails(vendorMaster);
        defaultComboBoxModel.addElement("N/A");
        
        for(VendorMaster vm: list)
            defaultComboBoxModel.addElement(vm.getName());
        
        vendorName.setModel(defaultComboBoxModel);
    }

    private void loadTable(String parameter, String searchType) 
    {
        DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
        defaultTableModel.setRowCount(0);
        
        DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        
        if(flag)
        {
            VendorMaster vendorMaster = new VendorMaster();
            VendorQuery vendorQuery = new VendorQuery();
            VendorBillMaster vendorBillMaster = new VendorBillMaster();
            VendorBillMasterQuery vendorBillMasterQuery = new VendorBillMasterQuery();

            if(searchType.equalsIgnoreCase("bill id"))
                vendorBillMaster.setId(Integer.parseInt(parameter));
            else
                if(searchType.equalsIgnoreCase("challan"))
                    vendorBillMaster.setChallan(parameter);
                else
                    if(searchType.equalsIgnoreCase("vendor"))
                    {
                        vendorMaster.setName(parameter);

                        List<VendorMaster> list = vendorQuery.getVendorDetails(vendorMaster);

                        for(VendorMaster vm: list)
                            vendorMaster.setId(vm.getId());

                        vendorBillMaster.setVendorMaster(vendorMaster);
                    }
                    else
                    {
                        Date fromDate = from.getDate();
                        Date toDate = to.getDate();

                        if(fromDate != null && toDate != null)
                        {
                            String stringFrom = dateFormat.format(fromDate);
                            String stringTo = dateFormat.format(toDate);

                            try
                            {
                                fromDate = dateFormat.parse(stringFrom);
                                toDate = dateFormat.parse(stringTo);
                                if(toDate.compareTo(fromDate) < 0)
                                {
                                    JOptionPane.showMessageDialog(null, MessageFormat.getMessage("To Date can't be ahead of From Date"), "Error Message", JOptionPane.ERROR_MESSAGE);
                                    return;
                                }
                                vendorBillMaster.setDate(fromDate);
                                vendorBillMaster.setTo(toDate);

                                List<Object[]> list = vendorBillMasterQuery.getPurchase(vendorBillMaster);

                                for(Object[] object: list)
                                {
                                    VendorBillMaster vbm = (VendorBillMaster) object[0];
                                    defaultTableModel.addRow(new Object[]{vbm.getVendorMaster().getId(), vbm.getId(), dateFormat.format(vbm.getDate()), vbm.getVendorMaster().getName(), vbm.getReference(), vbm.getChallan(), vbm.getBillAmount(), vbm.getDiscount(), vbm.getFinalBillAmount()});
                                }

                                jTable1.setModel(defaultTableModel);
                            }
                            catch(Exception e)
                            {

                            }
                        }
                        return;
                    }

            List<Object[]> list = vendorBillMasterQuery.getPurchase(vendorBillMaster);

            for(Object[] object: list)
            {
                VendorBillMaster vbm = (VendorBillMaster) object[0];
                defaultTableModel.addRow(new Object[]{vbm.getVendorMaster().getId(), vbm.getId(), dateFormat.format(vbm.getDate()), vbm.getVendorMaster().getName(), vbm.getChallan(), vbm.getReference(), vbm.getBillAmount(), vbm.getDiscount(), vbm.getFinalBillAmount()});
            }
        }
        
        else
        {
            CustomerMaster customerMaster = new CustomerMaster();
            CustomerMasterQuery customerMasterQuery = new CustomerMasterQuery();
            SaleMaster saleMaster = new SaleMaster();
            SaleMasterQuery saleMasterQuery = new SaleMasterQuery();
            
            if(searchType.equalsIgnoreCase("bill id"))
                saleMaster.setId(Integer.parseInt(parameter));
            else
                if(searchType.equalsIgnoreCase("vendor"))
                {
                    customerMaster.setName(parameter);
                    
                    List<CustomerMaster> list = customerMasterQuery.getCustomerDetails(customerMaster);
                    for(CustomerMaster cm: list)
                        customerMaster.setId(cm.getId());
                    
                    saleMaster.setCustomerMaster(customerMaster);
                }
                else
                {
                    Date fromDate = from.getDate();
                    Date toDate = to.getDate();

                    if(fromDate != null && toDate != null)
                    {
                        String stringFrom = dateFormat.format(fromDate);
                        String stringTo = dateFormat.format(toDate);

                        try
                        {
                            fromDate = dateFormat.parse(stringFrom);
                            toDate = dateFormat.parse(stringTo);
                            if(toDate.compareTo(fromDate) < 0)
                            {
                                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("To Date can't be ahead of From Date"), "Error Message", JOptionPane.ERROR_MESSAGE);
                                return;
                            }
                            saleMaster.setDate(fromDate);
                            saleMaster.setTo(toDate);

                            List<Object[]> list = saleMasterQuery.getSale(saleMaster);

                            for(Object[] object: list)
                            {
                                SaleMaster sm = (SaleMaster) object[0];
                                defaultTableModel.addRow(new Object[]{sm.getCustomerMaster().getId(), sm.getId(), dateFormat.format(sm.getDate()), sm.getCustomerMaster().getName(), sm.getReference(),"", sm.getBillAmount(), sm.getDiscount(), sm.getFinalBillAmount()});
                            }

                            jTable1.setModel(defaultTableModel);
                        }
                        catch(Exception e)
                        {

                        }
                    }
                    return;
                }
            
            List<Object[]> list = saleMasterQuery.getSale(saleMaster);

            for(Object[] object: list)
            {
                SaleMaster sm = (SaleMaster) object[0];
                defaultTableModel.addRow(new Object[]{sm.getCustomerMaster().getId(), sm.getId(), dateFormat.format(sm.getDate()), sm.getCustomerMaster().getName(), sm.getReference(), "", sm.getBillAmount(), sm.getDiscount(), sm.getFinalBillAmount()});
            }
        }
        jTable1.setModel(defaultTableModel);
    }

    private void billDetails() 
    {
        try
        {
            int billId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            
            if(flag)
            {
                PurchaseReturnBillDetails storeDetails = new PurchaseReturnBillDetails(billId, true);
                storeDetails.setTitle("Bill Details");
                jDesktopPane.add(storeDetails);
                SetDimension setDimension = new SetDimension();
                setDimension.setInternalFrameLocation(jDesktopPane, storeDetails);
                storeDetails.setVisible(true);
            }
            else
            {
                SaleReturnBillDetails storeDetails = new SaleReturnBillDetails(billId);
                storeDetails.setTitle("Bill Details");
                jDesktopPane.add(storeDetails);
                SetDimension setDimension = new SetDimension();
                setDimension.setInternalFrameLocation(jDesktopPane, storeDetails);
                storeDetails.setVisible(true);
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please select the row whose details you want to view"), "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadCustomer() 
    {
        CustomerMaster customerMaster = new CustomerMaster();
        CustomerMasterQuery customerMasterQuery = new CustomerMasterQuery();
        
        DefaultComboBoxModel defaultComboBoxModel = (DefaultComboBoxModel)vendorName.getModel();
        defaultComboBoxModel.addElement("N/A");
        List<CustomerMaster> list = customerMasterQuery.getCustomerDetails(customerMaster);
        for(CustomerMaster cm: list)
            defaultComboBoxModel.addElement(cm.getName());
        
        vendorName.setModel(defaultComboBoxModel);
    }
}
