/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.view;

import com.grocery.bean.ItemAvailability;
import com.grocery.bean.ItemMaster;
import com.grocery.bean.PurchaseReturn;
import com.grocery.bean.PurchaseReturnDetails;
import com.grocery.bean.SaleDetails;
import com.grocery.bean.SaleMaster;
import com.grocery.bean.StockDetails;
import com.grocery.bean.VendorBillMaster;
import com.grocery.bean.VendorMaster;
import com.grocery.query.ItemAvailabilityQuery;
import com.grocery.query.PurchaseReturnDetailsQuery;
import com.grocery.query.PurchaseReturnQuery;
import com.grocery.query.SaleDetailsQuery;
import com.grocery.query.StockDetailsQuery;
import com.grocery.query.VendorBillMasterQuery;
import com.grocery.query.VendorQuery;
import com.grocery.read.MessageFormat;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class PurchaseReturnBillDetails extends javax.swing.JInternalFrame {

    private boolean flag;
    private int billId;
    private Date date = new Date();
    
    public PurchaseReturnBillDetails(int id, boolean flag) {
        initComponents();
        this.flag = flag;
        this.billId = id;
        returnDate.setDate(date);
        if(!flag)
            jLabelPurchased.setText("Sold Items");
        
        jTable1.getTableHeader().setFont(new Font("Georgia", Font.BOLD, 11));
        jTable2.getTableHeader().setFont(new Font("Georgia", Font.BOLD, 11));
        
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        
        jTable1.getColumnModel().getColumn(1).setMinWidth(0);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(0);
        
        jTable2.getColumnModel().getColumn(0).setMinWidth(0);
        jTable2.getColumnModel().getColumn(0).setMaxWidth(0);
        
        jTable2.getColumnModel().getColumn(1).setMinWidth(0);
        jTable2.getColumnModel().getColumn(1).setMaxWidth(0);
        
        jTable2.getColumnModel().getColumn(8).setMinWidth(0);
        jTable2.getColumnModel().getColumn(8).setMaxWidth(0);   
        
        loadTable();
        getTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelPurchased = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        add = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        remove = new javax.swing.JButton();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        returnDate = new com.toedter.calendar.JDateChooser();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        remark = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bill Details");

        jLabelPurchased.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelPurchased.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPurchased.setText("Purchased Items:");

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Details Id", "Item Id", "Item Name", "Unit Price", "Quantity", "GST %", "GST Amount", "Final Total", "Available Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel17.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Returned Items:");

        jTable2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Details Id", "Item Id", "Item Name", "Unit Price", "Quantity", "GST %", "GST Amount", "Final Amount", "Index"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Total:");

        total.setEditable(false);
        total.setBackground(new java.awt.Color(255, 255, 153));
        total.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        total.setForeground(new java.awt.Color(255, 0, 0));
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add.setText("Return");
        add.setMnemonic(KeyEvent.VK_R);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        remove.setMnemonic(KeyEvent.VK_A);
        remove.setText("Add To Stock");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save.setMnemonic(KeyEvent.VK_S);
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel.setMnemonic(KeyEvent.VK_C);
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Return Date:");

        returnDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("Remark:");

        remark.setEditable(false);
        remark.setBackground(new java.awt.Color(255, 255, 153));
        remark.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        remark.setForeground(new java.awt.Color(255, 0, 0));
        remark.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(460, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(534, 534, 534))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(539, 539, 539))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPurchased)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(452, 452, 452)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(returnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPurchased, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(cancel))
                .addGap(169, 169, 169))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        cancel();
    }//GEN-LAST:event_cancelActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        add();
    }//GEN-LAST:event_addActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            add();
    }//GEN-LAST:event_jTable1KeyPressed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        remove();
    }//GEN-LAST:event_removeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        save();
    }//GEN-LAST:event_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPurchased;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField remark;
    private javax.swing.JButton remove;
    private com.toedter.calendar.JDateChooser returnDate;
    private javax.swing.JButton save;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    private void cancel() 
    {
        int confirm = JOptionPane.showConfirmDialog(null, MessageFormat.getMessage("Are you sure of Closing this form?"));
        if(confirm == JOptionPane.YES_OPTION)
            dispose();
    }

    private void loadTable() 
    {
        
        DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
        defaultTableModel.setRowCount(0);
        if(flag)
        {
            VendorBillMaster vendorBillMaster = new VendorBillMaster();
            vendorBillMaster.setId(billId);
            
            StockDetails stockDetails = new StockDetails();
            stockDetails.setVendorBillMaster(vendorBillMaster);
            
            StockDetailsQuery stockDetailsQuery = new StockDetailsQuery();
            
            List<Object[]> list = stockDetailsQuery.getPurchase(stockDetails);
            
            for(Object[] object: list)
            {
                StockDetails sd = (StockDetails)object[0];
                ItemAvailability ia = (ItemAvailability)object[4];  
                defaultTableModel.addRow(new Object[]{sd.getId(), sd.getItemMaster().getId(), sd.getItemMaster().getName(), sd.getUnitPrice(), sd.getQuantity(), sd.getGstPercent(), sd.getGstAmount(), sd.getFinalTotal(), ia.getAvailability()});
                remark.setText(sd.getVendorBillMaster().getRemark());
            }
            
            jTable1.setModel(defaultTableModel);
        }
    }

    private void getTotal() 
    {
        DecimalFormat decimalFormat = new DecimalFormat("#0.00");
        
        float sum = 0;
        int i = 0;
        
        while(i < jTable2.getRowCount())
        {
            sum = sum + Float.parseFloat(jTable2.getValueAt(i, 7).toString());
            i++;
        }
        
        total.setText(decimalFormat.format(sum));
    }

    private void add() 
    {
        DefaultTableModel defaultTableModel = (DefaultTableModel)jTable2.getModel();
        DefaultTableModel defaultTableModel1 = (DefaultTableModel)jTable1.getModel();
        try
        {
            DecimalFormat decimalFormat = new DecimalFormat("#0.000");
            DecimalFormat decimalFormat1 = new DecimalFormat("#0.00");
            
            int index = jTable1.getSelectedRow();
            int detailsId = Integer.parseInt(jTable1.getValueAt(index, 0).toString());
            int itemId = Integer.parseInt(jTable1.getValueAt(index, 1).toString());
            String itemName = jTable1.getValueAt(index, 2).toString();
            float unitPrice = Float.parseFloat(jTable1.getValueAt(index, 3).toString());
            float quantity = Float.parseFloat(jTable1.getValueAt(index, 4).toString());
            float gstPercent = Float.parseFloat(jTable1.getValueAt(index, 5).toString());
            float gstAmount = Float.parseFloat(jTable1.getValueAt(index, 6).toString());
            float finalTotal = Float.parseFloat(jTable1.getValueAt(index, 7).toString());
            float availableQuantity = Float.parseFloat(jTable1.getValueAt(index, 8).toString());
            
            float total = 0;
            
            float returnedQuantity = 0;
            float newTotal = 0;
            float newFinalTotal = 0;
            float newGstAmount = 0;
               
            JFrame frame = new JFrame("Input");
            
            try
            {
                returnedQuantity = Float.parseFloat(JOptionPane.showInputDialog(frame, "<HTML><FONT color=\"#000000\">Enter the quantity of: <strong><U>" + itemName + "</U></strong><br>Purchased Quantity = <strong><U>" + decimalFormat.format(quantity) + "</U></strong><br>Available Quantity = <strong><U>" + decimalFormat.format(availableQuantity) + "</FONT></HTML>" ));
                
                if(returnedQuantity > quantity)
                {
                    JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Returned Quantity can't be greater than Purchased Quantity"), "Error Message", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(returnedQuantity > availableQuantity)
                {
                    JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Returned Quantity can't be greater than Available Quantity"), "Error Message", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                newTotal = getTotal(unitPrice, returnedQuantity);
                newGstAmount = getGstAmount(gstPercent, newTotal);
                newFinalTotal = getFinalAmount(newGstAmount, newTotal);
                
                defaultTableModel.addRow(new Object[]{detailsId, itemId, itemName, unitPrice, decimalFormat.format(returnedQuantity), gstPercent, newGstAmount, decimalFormat1.format(newFinalTotal), index});
                
                jTable2.setModel(defaultTableModel);
                getTotal();
                
                quantity = quantity - returnedQuantity;
                total = getTotal(unitPrice, quantity);
                gstAmount = getGstAmount(gstPercent, total);
                finalTotal = getFinalAmount(gstAmount, total);
                
                defaultTableModel1.setValueAt(decimalFormat.format(quantity), index, 4);
                defaultTableModel1.setValueAt(decimalFormat1.format(gstAmount), index, 6);
                defaultTableModel1.setValueAt(decimalFormat1.format(finalTotal), index, 7);
                defaultTableModel1.setValueAt(decimalFormat.format(availableQuantity - returnedQuantity), index, 8);
                
                jTable1.setModel(defaultTableModel1);  
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please enter numeric value"), "Error Message", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please select the Item you want to return"), "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private float getTotal(float unitPrice, float quantity)
    {
        return (unitPrice * quantity);
    }
    
    private float getGstAmount(float gstPercent, float amount)
    {
        return ((gstPercent * amount)/100);
    }
    
    private float getFinalAmount(float gstAmount, float total)
    {
        return(gstAmount + total);
    }

    private void remove() 
    {
        DefaultTableModel defaultTableModel = (DefaultTableModel)jTable2.getModel();
        DefaultTableModel defaultTableModel1 = (DefaultTableModel)jTable1.getModel();
        try
        {
            DecimalFormat decimalFormat = new DecimalFormat("#0.000");
            DecimalFormat decimalFormat1 = new DecimalFormat("#0.00");
            
            int index = jTable2.getSelectedRow();
            int detailsId = Integer.parseInt(jTable2.getValueAt(index, 0).toString());
            int itemId = Integer.parseInt(jTable2.getValueAt(index, 1).toString());
            String itemName = jTable2.getValueAt(index, 2).toString();
            float unitPrice = Float.parseFloat(jTable2.getValueAt(index, 3).toString());
            float quantity = Float.parseFloat(jTable2.getValueAt(index, 4).toString());
            float gstPercent = Float.parseFloat(jTable2.getValueAt(index, 5).toString());
            float gstAmount = Float.parseFloat(jTable2.getValueAt(index, 6).toString());
            float finalTotal = Float.parseFloat(jTable2.getValueAt(index, 7).toString());
            int purchaseTableRow = Integer.parseInt(jTable2.getValueAt(index, 8).toString());
            
            float total = 0;
            float newGstAmount = 0;
            float newFinalTotal = 0;
            
            float newQuantity = Float.parseFloat(jTable1.getValueAt(purchaseTableRow, 4).toString()) + quantity;
            float newAvailability = Float.parseFloat(jTable1.getValueAt(purchaseTableRow, 8).toString()) + quantity;
            total = getTotal(unitPrice, newQuantity);
            newGstAmount = getGstAmount(gstPercent, total);
            newFinalTotal = getFinalAmount(newGstAmount, total);
            
            
            defaultTableModel1.setValueAt(decimalFormat.format(newQuantity), purchaseTableRow, 4);
            defaultTableModel1.setValueAt(decimalFormat1.format(newGstAmount), purchaseTableRow, 6);
            defaultTableModel1.setValueAt(decimalFormat1.format(newFinalTotal), purchaseTableRow, 7);
            defaultTableModel1.setValueAt(decimalFormat.format(newAvailability), purchaseTableRow, 8);
            
            jTable1.setModel(defaultTableModel1);
            
            defaultTableModel.removeRow(index);
            jTable2.setModel(defaultTableModel);
            getTotal();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please select the Item you want to remove"), "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void save() 
    {
        if(jTable2.getRowCount() == 0)
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("No items returned"), "Error Message", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(null, MessageFormat.getMessage("Are you sure of returning these stocks?"));
        if(confirm == JOptionPane.YES_OPTION)
        {
            if(flag)
            {
                VendorBillMaster vendorBillMaster = new VendorBillMaster();
                VendorBillMasterQuery vendorBillMasterQuery = new VendorBillMasterQuery();

                ItemMaster itemMaster = new ItemMaster();

                ItemAvailability itemAvailability = new ItemAvailability();
                ItemAvailabilityQuery itemAvailabilityQuery = new ItemAvailabilityQuery();

                StockDetails stockDetails = new StockDetails();
                StockDetailsQuery stockDetailsQuery = new StockDetailsQuery();

                VendorMaster vendorMaster = new VendorMaster();
                VendorQuery vendorQuery = new VendorQuery();

                PurchaseReturn purchaseReturn = new PurchaseReturn();
                PurchaseReturnQuery purchaseReturnQuery = new PurchaseReturnQuery();

                PurchaseReturnDetails purchaseReturnDetails = new PurchaseReturnDetails();
                PurchaseReturnDetailsQuery purchaseReturnDetailsQuery = new PurchaseReturnDetailsQuery();
                
                vendorBillMaster.setId(billId);

                List<Object[]> vendorBillMasterList = vendorBillMasterQuery.getPurchase(vendorBillMaster);

                for(Object[]object: vendorBillMasterList)
                {
                    VendorBillMaster vbm = (VendorBillMaster)object[0];

                    vendorBillMaster.setBillAmount(vbm.getBillAmount());
                    vendorBillMaster.setFinalBillAmount(vbm.getFinalBillAmount());

                    vendorMaster.setId(vbm.getVendorMaster().getId());
                    vendorMaster.setBalance(vbm.getVendorMaster().getBalance());
                }
                
                vendorBillMaster.setBillAmount(vendorBillMaster.getBillAmount().subtract(new BigDecimal(total.getText())));
                vendorBillMaster.setFinalBillAmount(vendorBillMaster.getFinalBillAmount().subtract(new BigDecimal(total.getText())));
                
                vendorBillMasterQuery.updateVendorBillMaster(vendorBillMaster);
                
                vendorMaster.setBalance(vendorMaster.getBalance().subtract(new BigDecimal(total.getText())));
                vendorQuery.updateVendorBalance(vendorMaster);

                int i = 0;
                while(i < jTable1.getRowCount())
                {
                    int detailsId = Integer.parseInt(jTable1.getValueAt(i, 0).toString());
                    int itemId = Integer.parseInt(jTable1.getValueAt(i, 1).toString());
                    String itemName = jTable1.getValueAt(i, 2).toString();
                    float unitPrice = Float.parseFloat(jTable1.getValueAt(i, 3).toString());
                    float quantity = Float.parseFloat(jTable1.getValueAt(i, 4).toString());
                    float gstPercent = Float.parseFloat(jTable1.getValueAt(i, 5).toString());
                    float gstAmount = Float.parseFloat(jTable1.getValueAt(i, 6).toString());
                    float finalTotal = Float.parseFloat(jTable1.getValueAt(i, 7).toString());
                    float availableQuantity = Float.parseFloat(jTable1.getValueAt(i, 8).toString());

                    stockDetails.setId(detailsId);
                    stockDetails.setQuantity(new BigDecimal(quantity));
                    stockDetails.setGstAmount(new BigDecimal(gstAmount));
                    stockDetails.setFinalTotal(new BigDecimal(finalTotal));

                    stockDetailsQuery.updateStockDetails(stockDetails);

                    itemMaster.setId(itemId);

                    itemAvailability.setItemMaster(itemMaster);

                    List<ItemAvailability> itemAvailabilityList = itemAvailabilityQuery.checkItem(itemAvailability);

                    for(ItemAvailability ia: itemAvailabilityList)
                        itemAvailability.setId(ia.getId());

                    itemAvailability.setAvailability(new BigDecimal(availableQuantity));
                    itemAvailability.setThreshold(new BigDecimal(getThreshold(availableQuantity)));

                    itemAvailabilityQuery.updateItemAvailability(itemAvailability);

                    i++;
                }
                
                i = 0;
                
                purchaseReturn.setDate(returnDate.getDate());
                purchaseReturn.setVendorBillMaster(vendorBillMaster);
                purchaseReturn.setAmount(new BigDecimal(total.getText()));
                
                purchaseReturnQuery.insertIntoPurchaseReturnDetails(purchaseReturn);
                
                while(i < jTable2.getRowCount())
                {
                    int detailsId = Integer.parseInt(jTable1.getValueAt(i, 0).toString());
                    int itemId = Integer.parseInt(jTable1.getValueAt(i, 1).toString());
                    String itemName = jTable1.getValueAt(i, 2).toString();
                    float unitPrice = Float.parseFloat(jTable1.getValueAt(i, 3).toString());
                    float quantity = Float.parseFloat(jTable1.getValueAt(i, 4).toString());
                    float gstPercent = Float.parseFloat(jTable1.getValueAt(i, 5).toString());
                    float gstAmount = Float.parseFloat(jTable1.getValueAt(i, 6).toString());
                    float finalTotal = Float.parseFloat(jTable1.getValueAt(i, 7).toString());
                    
                    itemMaster.setId(itemId);
                    
                    purchaseReturnDetails.setPurchaseReturn(purchaseReturn);
                    purchaseReturnDetails.setItemMaster(itemMaster);
                    purchaseReturnDetails.setUnitPrice(new BigDecimal(unitPrice));
                    purchaseReturnDetails.setQuantity(new BigDecimal(quantity));
                    purchaseReturnDetails.setGstPercent(new BigDecimal(gstPercent));
                    purchaseReturnDetails.setGstAmount(new BigDecimal(gstAmount));
                    purchaseReturnDetails.setFinalTotal(new BigDecimal(finalTotal));
                    
                    purchaseReturnDetailsQuery.insertIntoPurchaseReturnDetails(purchaseReturnDetails);

                    i++;
                }
                
            }
            
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Stocks returned successfully"));
            dispose();
        }
    }
    
    public float getThreshold(float quantity)
    {
        return (float)(0.25 * quantity);
    }
}
