/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.view;


import com.grocery.bean.Expenses;
import com.grocery.bean.VendorMaster;
import com.grocery.bean.VendorPartialPayment;
import com.grocery.query.BeginningCashQuery;
import com.grocery.query.ExpensesQuery;
import com.grocery.query.VendorPartialPaymentQuery;
import com.grocery.query.VendorQuery;
import com.grocery.read.MessageFormat;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class VendorChequeClearanceView extends javax.swing.JInternalFrame {

    private Date currentDate = new Date();
    private JTextFieldDateEditor editor;
    private BigDecimal beginningCash;
    private BigDecimal expenses;
    
    public VendorChequeClearanceView() {
        initComponents();
        editor = (JTextFieldDateEditor)date.getDateEditor();
        editor.setEditable(false);
        date.setDate(currentDate);
        
        jTable1.getTableHeader().setFont(new Font("Georgia", Font.BOLD, 11));
        clear.setEnabled(false);
        bounce.setEnabled(false);
        loadBeginningCash();
        loadExpenses();
        loadCash();
        
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(1).setMinWidth(0);
        jTable1.getColumnModel().getColumn(1).setMaxWidth(0);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        availableCash = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        bounce = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePropertyChange(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Date:");

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Vendor Id", "Date ", "Vendor Name", "Cheque/NEFT Date", "Payment Mode", "Cheque/NEFT Number", "Bank", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel31.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Available Cash:");

        availableCash.setEditable(false);
        availableCash.setBackground(new java.awt.Color(255, 255, 153));
        availableCash.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        availableCash.setForeground(new java.awt.Color(255, 0, 0));
        availableCash.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setText("Clear");
        clear.setMnemonic(KeyEvent.VK_C);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        clear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clearKeyPressed(evt);
            }
        });

        bounce.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bounce.setText("Bounce");
        bounce.setMnemonic(KeyEvent.VK_B);
        bounce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bounceActionPerformed(evt);
            }
        });
        bounce.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bounceKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(10, 10, 10)
                .addComponent(availableCash, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bounce, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear)
                    .addComponent(bounce))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePropertyChange
        clear.setEnabled(false);
        loadDetails();
    }//GEN-LAST:event_datePropertyChange

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Date date = new Date();
        int index = jTable1.getSelectedRow();
        DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        try
        {
             Date chequeDate = dateFormat.parse(jTable1.getValueAt(index, 4).toString());
             if(chequeDate.compareTo(date) <= 0)
             {
                 clear.setEnabled(true);
                 bounce.setEnabled(true);
             }
             else
             {
                 clear.setEnabled(false);
                 bounce.setEnabled(false);
             }
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clearAmount();
    }//GEN-LAST:event_clearActionPerformed

    private void clearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clearKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            clearAmount();
    }//GEN-LAST:event_clearKeyPressed

    private void bounceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bounceActionPerformed
        bounceCheque();
    }//GEN-LAST:event_bounceActionPerformed

    private void bounceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bounceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bounceKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availableCash;
    private javax.swing.JButton bounce;
    private javax.swing.JButton clear;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
    private void loadBeginningCash() 
    {
        BeginningCashQuery beginningCashQuery = new BeginningCashQuery();
        
        List<BigDecimal> list = beginningCashQuery.getBeginningCash();
        
        for(BigDecimal bd: list)
            beginningCash = bd;
    }

    private void loadExpenses() 
    {
        ExpensesQuery expensesQuery = new ExpensesQuery();
        
        List<BigDecimal> list = expensesQuery.getExpenses();
        
        for(BigDecimal bd: list)
            expenses = bd;
    }

    private void loadCash() 
    {
        availableCash.setText(String.valueOf(beginningCash.subtract(expenses)));
    }

    private void loadDetails() 
    {
        DefaultTableModel defaultTableModel = (DefaultTableModel)jTable1.getModel();
        defaultTableModel.setRowCount(0);
        
        DateFormat dateFormat = new SimpleDateFormat("dd-MMM-yyyy");
        Date date = this.date.getDate();
        
        VendorPartialPayment vendorPartialPayment = new VendorPartialPayment();
        vendorPartialPayment.setChequeDate(date);
        
        VendorPartialPaymentQuery vendorPartialPaymentQuery = new VendorPartialPaymentQuery();
        
        List<Object[]> list = vendorPartialPaymentQuery.getDetails(vendorPartialPayment);
        
        for(Object[] object: list)
        {
            VendorPartialPayment vpp = (VendorPartialPayment)object[0];
                defaultTableModel.addRow(new Object[]{vpp.getId(), vpp.getVendorMaster().getId(), dateFormat.format(vpp.getDate()), vpp.getVendorMaster().getName(), dateFormat.format(vpp.getChequeDate()), vpp.getPaymentMode(), vpp.getChequeCardNumber(), vpp.getBank(), vpp.getPaidAmount()});
        }
        jTable1.setModel(defaultTableModel);
    }

     private void clearAmount() 
    {
        try
        {
            
            String vendorName = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
            int vendorId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            BigDecimal amount = new BigDecimal(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            int partialId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            
            int compare = amount.compareTo(new BigDecimal(availableCash.getText()));
            if(compare == 1)
            {
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Insufficient Funds!!\nCheque Clearance failed"), "Error Message", JOptionPane.ERROR_MESSAGE);
                return;
            }
            int confirm = JOptionPane.showConfirmDialog(null, MessageFormat.getMessage("Are you sure of clearing this Cheque?"));
        
            if(confirm == JOptionPane.YES_OPTION)
            {
                VendorPartialPayment vendorPartialPayment = new VendorPartialPayment();
                VendorPartialPaymentQuery vendorPartialPaymentQuery = new VendorPartialPaymentQuery();
                
                vendorPartialPayment.setChequeClearanceDate(currentDate);
                vendorPartialPayment.setStatus("1");
                vendorPartialPayment.setId(partialId);
                
                vendorPartialPaymentQuery.updateVendorPartialPayment(vendorPartialPayment);
                
                Expenses expenses = new Expenses(currentDate, amount, "Cheque Clearance for Vendor: " + vendorName);
                ExpensesQuery expensesQuery = new ExpensesQuery();
                expensesQuery.insertIntoExpenses(expenses);
                
                VendorMaster vendorMaster = new VendorMaster();
                vendorMaster.setName(vendorName);
                vendorMaster.setId(vendorId);
                
                VendorQuery vendorQuery = new VendorQuery();
                
                List<VendorMaster> list = vendorQuery.getVendorDetails(vendorMaster);
                
                for(VendorMaster vm: list)
                    vendorMaster.setBalance(vm.getBalance().subtract(amount));
                
                vendorQuery.updateVendorBalance(vendorMaster);
                
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Vendor Cheque Clearance successful"));
                clear();
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please select the Cheque/NEFT you want to clear"), "Error Message", JOptionPane.ERROR_MESSAGE);
            clear();
        }
    }
    
    public void clear()
    {
        clear.setEnabled(false);
        bounce.setEnabled(false);
        loadDetails();
        loadBeginningCash();
        loadExpenses();
        loadCash();
    }
    
    private void bounceCheque() 
    {
        try
        {
            
            String vendorName = jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString();
            int vendorId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            BigDecimal amount = new BigDecimal(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            int partialId = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
            
            int confirm = JOptionPane.showConfirmDialog(null, MessageFormat.getMessage("Are you sure that this Cheque bounced?"));
        
            if(confirm == JOptionPane.YES_OPTION)
            {
                VendorPartialPayment vendorPartialPayment = new VendorPartialPayment();
                VendorPartialPaymentQuery vendorPartialPaymentQuery = new VendorPartialPaymentQuery();
                
                vendorPartialPayment.setChequeClearanceDate(currentDate);
                vendorPartialPayment.setStatus("2");
                vendorPartialPayment.setId(partialId);
                
                vendorPartialPaymentQuery.updateVendorPartialPayment(vendorPartialPayment);
                
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Vendor Cheque Clearance successful"));
                clear();
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please select the Cheque/NEFT you want to clear"), "Error Message", JOptionPane.ERROR_MESSAGE);
            clear();
        }
    }
}
