package com.grocery.bean;
// Generated Mar 27, 2018 12:20:04 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SaleMaster generated by hbm2java
 */
public class SaleMaster  implements java.io.Serializable {


     private Integer id;
     private Counter counter;
     private CustomerMaster customerMaster;
     private StoreDetails storeDetails;
     private Date date;
     private Date to;
     private BigDecimal billAmount;
     private BigDecimal discount;
     private BigDecimal finalBillAmount;
     private String status;
     private String remark;
     private String reference;
     private Set saleDetailses = new HashSet(0);
     private Set saleReturns = new HashSet(0);

    public SaleMaster() {
    }

    public SaleMaster(Counter counter, CustomerMaster customerMaster, StoreDetails storeDetails, Date date, BigDecimal billAmount, BigDecimal discount, BigDecimal finalBillAmount, String status, String remark, Set saleDetailses, Set saleReturns) {
       this.counter = counter;
       this.customerMaster = customerMaster;
       this.storeDetails = storeDetails;
       this.date = date;
       this.billAmount = billAmount;
       this.discount = discount;
       this.finalBillAmount = finalBillAmount;
       this.status = status;
       this.remark = remark;
       this.saleDetailses = saleDetailses;
       this.saleReturns = saleReturns;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Counter getCounter() {
        return this.counter;
    }
    
    public void setCounter(Counter counter) {
        this.counter = counter;
    }
    public CustomerMaster getCustomerMaster() {
        return this.customerMaster;
    }
    
    public void setCustomerMaster(CustomerMaster customerMaster) {
        this.customerMaster = customerMaster;
    }
    public StoreDetails getStoreDetails() {
        return this.storeDetails;
    }
    
    public void setStoreDetails(StoreDetails storeDetails) {
        this.storeDetails = storeDetails;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public BigDecimal getBillAmount() {
        return this.billAmount;
    }
    
    public void setBillAmount(BigDecimal billAmount) {
        this.billAmount = billAmount;
    }
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }
    public BigDecimal getFinalBillAmount() {
        return this.finalBillAmount;
    }
    
    public void setFinalBillAmount(BigDecimal finalBillAmount) {
        this.finalBillAmount = finalBillAmount;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getSaleDetailses() {
        return this.saleDetailses;
    }
    
    public void setSaleDetailses(Set saleDetailses) {
        this.saleDetailses = saleDetailses;
    }
    public Set getSaleReturns() {
        return this.saleReturns;
    }
    
    public void setSaleReturns(Set saleReturns) {
        this.saleReturns = saleReturns;
    }

    /**
     * @return the to
     */
    public Date getTo() {
        return to;
    }

    /**
     * @param to the to to set
     */
    public void setTo(Date to) {
        this.to = to;
    }

    /**
     * @return the reference
     */
    public String getReference() {
        return reference;
    }

    /**
     * @param reference the reference to set
     */
    public void setReference(String reference) {
        this.reference = reference;
    }




}


