package com.grocery.bean;
// Generated Mar 27, 2018 12:20:04 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SaleReturn generated by hbm2java
 */
public class SaleReturn  implements java.io.Serializable {


     private Integer id;
     private SaleMaster saleMaster;
     private Date date;
     private Date to;
     private BigDecimal amount;
     private String remark;
     private Set saleReturnDetailses = new HashSet(0);

    public SaleReturn() {
    }

    public SaleReturn(SaleMaster saleMaster, Date date, BigDecimal amount, Set saleReturnDetailses) {
       this.saleMaster = saleMaster;
       this.date = date;
       this.amount = amount;
       this.saleReturnDetailses = saleReturnDetailses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SaleMaster getSaleMaster() {
        return this.saleMaster;
    }
    
    public void setSaleMaster(SaleMaster saleMaster) {
        this.saleMaster = saleMaster;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Set getSaleReturnDetailses() {
        return this.saleReturnDetailses;
    }
    
    public void setSaleReturnDetailses(Set saleReturnDetailses) {
        this.saleReturnDetailses = saleReturnDetailses;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the to
     */
    public Date getTo() {
        return to;
    }

    /**
     * @param to the to to set
     */
    public void setTo(Date to) {
        this.to = to;
    }




}


