package com.grocery.bean;
// Generated Mar 27, 2018 12:20:04 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VendorBillMaster generated by hbm2java
 */
public class VendorBillMaster  implements java.io.Serializable {


     private Integer id;
     private StoreDetails storeDetails;
     private VendorMaster vendorMaster;
     private Date date;
     private Date to;
     private String challan;
     private BigDecimal billAmount;
     private BigDecimal discount;
     private BigDecimal finalBillAmount;
     private String remark;
     private String reference;
     private Set purchaseReturns = new HashSet(0);
     private Set stockDetailses = new HashSet(0);

    public VendorBillMaster() {
    }

    public VendorBillMaster(StoreDetails storeDetails, VendorMaster vendorMaster, Date date, String challan, BigDecimal billAmount, BigDecimal discount, BigDecimal finalBillAmount, String remark, Set purchaseReturns, Set stockDetailses) {
       this.storeDetails = storeDetails;
       this.vendorMaster = vendorMaster;
       this.date = date;
       this.challan = challan;
       this.billAmount = billAmount;
       this.discount = discount;
       this.finalBillAmount = finalBillAmount;
       this.remark = remark;
       this.purchaseReturns = purchaseReturns;
       this.stockDetailses = stockDetailses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public StoreDetails getStoreDetails() {
        return this.storeDetails;
    }
    
    public void setStoreDetails(StoreDetails storeDetails) {
        this.storeDetails = storeDetails;
    }
    public VendorMaster getVendorMaster() {
        return this.vendorMaster;
    }
    
    public void setVendorMaster(VendorMaster vendorMaster) {
        this.vendorMaster = vendorMaster;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getChallan() {
        return this.challan;
    }
    
    public void setChallan(String challan) {
        this.challan = challan;
    }
    public BigDecimal getBillAmount() {
        return this.billAmount;
    }
    
    public void setBillAmount(BigDecimal billAmount) {
        this.billAmount = billAmount;
    }
    public BigDecimal getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }
    public BigDecimal getFinalBillAmount() {
        return this.finalBillAmount;
    }
    
    public void setFinalBillAmount(BigDecimal finalBillAmount) {
        this.finalBillAmount = finalBillAmount;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public Set getPurchaseReturns() {
        return this.purchaseReturns;
    }
    
    public void setPurchaseReturns(Set purchaseReturns) {
        this.purchaseReturns = purchaseReturns;
    }
    public Set getStockDetailses() {
        return this.stockDetailses;
    }
    
    public void setStockDetailses(Set stockDetailses) {
        this.stockDetailses = stockDetailses;
    }

    /**
     * @return the to
     */
    public Date getTo() {
        return to;
    }

    /**
     * @param to the to to set
     */
    public void setTo(Date to) {
        this.to = to;
    }

    /**
     * @return the reference
     */
    public String getReference() {
        return reference;
    }

    /**
     * @param reference the reference to set
     */
    public void setReference(String reference) {
        this.reference = reference;
    }

}


