package com.grocery.bean;
// Generated Mar 28, 2020 3:09:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Counter generated by hbm2java
 */
public class Counter  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String status;
     private Set saleMasters = new HashSet(0);

    public Counter() {
    }

    public Counter(String name, String status, Set saleMasters) {
       this.name = name;
       this.status = status;
       this.saleMasters = saleMasters;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getSaleMasters() {
        return this.saleMasters;
    }
    
    public void setSaleMasters(Set saleMasters) {
        this.saleMasters = saleMasters;
    }




}


