package com.grocery.bean;
// Generated Mar 28, 2020 3:09:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PurchaseReturn generated by hbm2java
 */
public class PurchaseReturn  implements java.io.Serializable {


     private Integer id;
     private VendorBillMaster vendorBillMaster;
     private BigDecimal amount;
     private Date date;
     private Date to;
     private Set purchaseReturnDetailses = new HashSet(0);

    public PurchaseReturn() {
    }

    public PurchaseReturn(Integer id, VendorBillMaster vendorBillMaster, BigDecimal amount, Date date, Date to) {
        this.id = id;
        this.vendorBillMaster = vendorBillMaster;
        this.amount = amount;
        this.date = date;
        this.to = to;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public VendorBillMaster getVendorBillMaster() {
        return vendorBillMaster;
    }

    public void setVendorBillMaster(VendorBillMaster vendorBillMaster) {
        this.vendorBillMaster = vendorBillMaster;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Date getTo() {
        return to;
    }

    public void setTo(Date to) {
        this.to = to;
    }

    public Set getPurchaseReturnDetailses() {
        return purchaseReturnDetailses;
    }

    public void setPurchaseReturnDetailses(Set purchaseReturnDetailses) {
        this.purchaseReturnDetailses = purchaseReturnDetailses;
    }

   
}


