package com.grocery.bean;
// Generated Mar 28, 2020 3:09:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SaleMaster generated by hbm2java
 */
public class SaleMaster  implements java.io.Serializable {


     private Integer id;
     private Counter counter;
     private CustomerDetails customerDetails;
     private StoreDetails storeDetails;
     private Date date;
     private Date to;
     private BigDecimal billAmount;
     private BigDecimal gstAmount;
     private BigDecimal discount;
     private BigDecimal finalBillAmount;
     private String status;
     private String remark;
     private String reference;
     private BigDecimal igstAmount;
     private String gstType;
     private String barCodeFlag;
     private Set saleDetailses = new HashSet(0);
     private Set saleReturns = new HashSet(0);

    public SaleMaster() {
    }

    public SaleMaster(Integer id, Counter counter, CustomerDetails customerDetails, StoreDetails storeDetails, Date date, Date to, BigDecimal billAmount, BigDecimal gstAmount, BigDecimal discount, BigDecimal finalBillAmount, String status, String remark, String reference, BigDecimal igstAmount, String gstType, String barCodeFlag) {
        this.id = id;
        this.counter = counter;
        this.customerDetails = customerDetails;
        this.storeDetails = storeDetails;
        this.date = date;
        this.to = to;
        this.billAmount = billAmount;
        this.gstAmount = gstAmount;
        this.discount = discount;
        this.finalBillAmount = finalBillAmount;
        this.status = status;
        this.remark = remark;
        this.reference = reference;
        this.igstAmount = igstAmount;
        this.gstType = gstType;
        this.barCodeFlag = barCodeFlag;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Counter getCounter() {
        return counter;
    }

    public void setCounter(Counter counter) {
        this.counter = counter;
    }

    public CustomerDetails getCustomerDetails() {
        return customerDetails;
    }

    public void setCustomerDetails(CustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
    }

    public StoreDetails getStoreDetails() {
        return storeDetails;
    }

    public void setStoreDetails(StoreDetails storeDetails) {
        this.storeDetails = storeDetails;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Date getTo() {
        return to;
    }

    public void setTo(Date to) {
        this.to = to;
    }

    public BigDecimal getBillAmount() {
        return billAmount;
    }

    public void setBillAmount(BigDecimal billAmount) {
        this.billAmount = billAmount;
    }

    public BigDecimal getGstAmount() {
        return gstAmount;
    }

    public void setGstAmount(BigDecimal gstAmount) {
        this.gstAmount = gstAmount;
    }

    public BigDecimal getDiscount() {
        return discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    public BigDecimal getFinalBillAmount() {
        return finalBillAmount;
    }

    public void setFinalBillAmount(BigDecimal finalBillAmount) {
        this.finalBillAmount = finalBillAmount;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public BigDecimal getIgstAmount() {
        return igstAmount;
    }

    public void setIgstAmount(BigDecimal igstAmount) {
        this.igstAmount = igstAmount;
    }

    public String getGstType() {
        return gstType;
    }

    public void setGstType(String gstType) {
        this.gstType = gstType;
    }

    public String getBarCodeFlag() {
        return barCodeFlag;
    }

    public void setBarCodeFlag(String barCodeFlag) {
        this.barCodeFlag = barCodeFlag;
    }

    public Set getSaleDetailses() {
        return saleDetailses;
    }

    public void setSaleDetailses(Set saleDetailses) {
        this.saleDetailses = saleDetailses;
    }

    public Set getSaleReturns() {
        return saleReturns;
    }

    public void setSaleReturns(Set saleReturns) {
        this.saleReturns = saleReturns;
    }

    
}


