package com.grocery.bean;
// Generated Mar 28, 2020 3:09:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SaleDetails generated by hbm2java
 */
public class SaleDetails  implements java.io.Serializable {
 private Integer id;
     private ItemMaster itemMaster;
     private SaleMaster saleMaster;
     private BigDecimal unitPrice;
     private BigDecimal sellingPrice;
     private BigDecimal quantity;
     private BigDecimal gstPercent;
     private BigDecimal igstPercent;
     private BigDecimal total;
     private BigDecimal finalSellingPrice;
     private String gstType;

    public SaleDetails() {
    }

    public SaleDetails(ItemMaster itemMaster, SaleMaster saleMaster, BigDecimal unitPrice, BigDecimal sellingPrice, BigDecimal quantity, BigDecimal gstPercent, BigDecimal igstPercent, BigDecimal total, BigDecimal finalSellingPrice, String gstType) {
       this.itemMaster = itemMaster;
       this.saleMaster = saleMaster;
       this.unitPrice = unitPrice;
       this.sellingPrice = sellingPrice;
       this.quantity = quantity;
       this.gstPercent = gstPercent;
       this.igstPercent = igstPercent;
       this.total = total;
       this.finalSellingPrice = finalSellingPrice;
       this.gstType = gstType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ItemMaster getItemMaster() {
        return this.itemMaster;
    }
    
    public void setItemMaster(ItemMaster itemMaster) {
        this.itemMaster = itemMaster;
    }
    public SaleMaster getSaleMaster() {
        return this.saleMaster;
    }
    
    public void setSaleMaster(SaleMaster saleMaster) {
        this.saleMaster = saleMaster;
    }
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    public BigDecimal getSellingPrice() {
        return this.sellingPrice;
    }
    
    public void setSellingPrice(BigDecimal sellingPrice) {
        this.sellingPrice = sellingPrice;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public BigDecimal getGstPercent() {
        return this.gstPercent;
    }
    
    public void setGstPercent(BigDecimal gstPercent) {
        this.gstPercent = gstPercent;
    }
    public BigDecimal getIgstPercent() {
        return this.igstPercent;
    }
    
    public void setIgstPercent(BigDecimal igstPercent) {
        this.igstPercent = igstPercent;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public BigDecimal getFinalSellingPrice() {
        return this.finalSellingPrice;
    }
    
    public void setFinalSellingPrice(BigDecimal finalSellingPrice) {
        this.finalSellingPrice = finalSellingPrice;
    }
    public String getGstType() {
        return this.gstType;
    }
    
    public void setGstType(String gstType) {
        this.gstType = gstType;
    }

}


