package com.grocery.bean;
// Generated Mar 28, 2020 3:09:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * StockDetails generated by hbm2java
 */
public class StockDetailsPurchase  implements java.io.Serializable {

//stock_details_purchase
//    StockDetailsPurchase
     private Integer id;
     private PurchaseMaster purchaseMaster;
     private VendorBillMaster vendorBillMaster;
     private BigDecimal quantity;
     private BigDecimal actualAmount;
     private BigDecimal gstPercent;
     private BigDecimal gstAmount;
     private BigDecimal finalTotal;
     private BigDecimal igstPercent;
     private BigDecimal igstAmount;
     private BigDecimal discount;

    public StockDetailsPurchase() {
    }

    public StockDetailsPurchase(Integer id, PurchaseMaster purchaseMaster, VendorBillMaster vendorBillMaster, BigDecimal quantity, BigDecimal actualAmount, BigDecimal gstPercent, BigDecimal gstAmount, BigDecimal finalTotal, BigDecimal igstPercent, BigDecimal igstAmount, BigDecimal discount) {
        this.id = id;
        this.purchaseMaster = purchaseMaster;
        this.vendorBillMaster = vendorBillMaster;
        this.quantity = quantity;
        this.actualAmount = actualAmount;
        this.gstPercent = gstPercent;
        this.gstAmount = gstAmount;
        this.finalTotal = finalTotal;
        this.igstPercent = igstPercent;
        this.igstAmount = igstAmount;
        this.discount = discount;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public PurchaseMaster getPurchaseMaster() {
        return purchaseMaster;
    }

    public void setPurchaseMaster(PurchaseMaster purchaseMaster) {
        this.purchaseMaster = purchaseMaster;
    }

    public VendorBillMaster getVendorBillMaster() {
        return vendorBillMaster;
    }

    public void setVendorBillMaster(VendorBillMaster vendorBillMaster) {
        this.vendorBillMaster = vendorBillMaster;
    }

    public BigDecimal getQuantity() {
        return quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getActualAmount() {
        return actualAmount;
    }

    public void setActualAmount(BigDecimal actualAmount) {
        this.actualAmount = actualAmount;
    }

    public BigDecimal getGstPercent() {
        return gstPercent;
    }

    public void setGstPercent(BigDecimal gstPercent) {
        this.gstPercent = gstPercent;
    }

    public BigDecimal getGstAmount() {
        return gstAmount;
    }

    public void setGstAmount(BigDecimal gstAmount) {
        this.gstAmount = gstAmount;
    }

    public BigDecimal getFinalTotal() {
        return finalTotal;
    }

    public void setFinalTotal(BigDecimal finalTotal) {
        this.finalTotal = finalTotal;
    }

    public BigDecimal getIgstPercent() {
        return igstPercent;
    }

    public void setIgstPercent(BigDecimal igstPercent) {
        this.igstPercent = igstPercent;
    }

    public BigDecimal getIgstAmount() {
        return igstAmount;
    }

    public void setIgstAmount(BigDecimal igstAmount) {
        this.igstAmount = igstAmount;
    }

    public BigDecimal getDiscount() {
        return discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

  
}


