/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.view;
import com.grocery.dimension.SetDimension;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.VK_E;
import static java.awt.event.KeyEvent.VK_M;
import static java.awt.event.KeyEvent.VK_S;

/**
 *
 * @author Admin
 */
public class HomePage1 extends javax.swing.JFrame {

    public HomePage1() {
        initComponents();

        jMenuItem5.setVisible(false);
        jMenuItem20.setVisible(false);
        
        jMenuItem11.setVisible(false);
        jMenuItem3.setVisible(false);
        jMenuItem6.setVisible(false);
        jMenuItem27.setVisible(false);
        jMenuItem13.setVisible(false);
        
        jMenuItem13.setVisible(false);
        jMenuItem13.setVisible(false);
        jMenuItem25.setVisible(false);
        jMenuItem21.setVisible(false);
        jMenuItem26.setVisible(false);
        
        jMenuItem2.setVisible(false);
       
        jMenuItem8.setVisible(false);
         
        jMenuItem19.setVisible(false);
        jMenuItem16.setVisible(false);
     //   jMenu10.setVisible(false);
        
        jMenuItem18.setVisible(false);
       // jMenu4.setVisible(false);
        jMenu18.setVisible(false);
        // jMenuItem21.setVisible(false);
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        double width = screenSize.getWidth();
        double height = screenSize.getHeight();
        jDesktopPane1.setSize((int) width, (int) height);
        jPanel4.setSize((int) width, (int) height);
        jLabelImage.setSize((int) width, (int) height);
    }

    HomePage1(String uname, int id) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(null);

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hdIamges/heart-healthy-mix_400_343 (2).jpg"))); // NOI18N
        jLabelImage.setText("jLabel5");
        jPanel4.add(jLabelImage);
        jLabelImage.setBounds(-6, -6, 1610, 1243);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1598, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jMenuBar1.setInheritsPopupMenu(true);
        jMenuBar1.setMaximumSize(new java.awt.Dimension(913, 32775));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/home.png"))); // NOI18N
        jMenu1.setText("घर");
        jMenu1.setToolTipText(" Home");
        jMenu1.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setIconTextGap(1);
        jMenu1.setPreferredSize(new java.awt.Dimension(93, 90));
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu1.setMnemonic(VK_M);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/online-store.png"))); // NOI18N
        jMenuItem2.setText("Store Details");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/online-store.png"))); // NOI18N
        jMenuItem3.setText("Item Details");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu6.setEnabled(false);
        jMenu6.setFocusable(false);
        jMenu6.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu6);

        jMenu23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/vendor.png"))); // NOI18N
        jMenu23.setText("विक्रेता जानकारी");
        jMenu23.setToolTipText("Vendor Info.");
        jMenu23.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenu23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu23.setIconTextGap(1);
        jMenu23.setMaximumSize(new java.awt.Dimension(99, 32767));
        jMenu23.setPreferredSize(new java.awt.Dimension(87, 100));
        jMenu23.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu23MouseClicked(evt);
            }
        });
        jMenu23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu23KeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu23);

        jMenu7.setEnabled(false);
        jMenu7.setFocusable(false);
        jMenu7.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu7);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/purchase management.png"))); // NOI18N
        jMenu2.setText("खरीद फरोख्त");
        jMenu2.setToolTipText("Purchase");
        jMenu2.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setIconTextGap(1);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu2.setMnemonic(VK_S);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/shopping-cart.png"))); // NOI18N
        jMenuItem5.setText("Purchase Item");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/pay32.png"))); // NOI18N
        jMenuItem20.setText("Purchase New");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem20);

        jMenuBar1.add(jMenu2);

        jMenu17.setEnabled(false);
        jMenu17.setFocusable(false);
        jMenu17.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu17);

        jMenu15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/purchase management.png"))); // NOI18N
        jMenu15.setText("काउंटर");
        jMenu15.setToolTipText("counter");
        jMenu15.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu15.setIconTextGap(1);
        jMenu15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu2.setMnemonic(VK_S);
        jMenu15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu15MouseClicked(evt);
            }
        });

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/shopping-cart.png"))); // NOI18N
        jMenuItem6.setText("Purchase Item");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem6);

        jMenuItem27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/pay32.png"))); // NOI18N
        jMenuItem27.setText("Purchase Payment");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem27);

        jMenuBar1.add(jMenu15);

        jMenu14.setEnabled(false);
        jMenu14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu14.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu14);

        jMenu16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/sales.png"))); // NOI18N
        jMenu16.setText(" बिक्री");
        jMenu16.setToolTipText("Sales");
        jMenu16.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu16.setIconTextGap(1);
        jMenu16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu4.setMnemonic(VK_E);
        jMenu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu16MouseClicked(evt);
            }
        });

        jMenuItem21.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/sale.png"))); // NOI18N
        jMenuItem21.setText("बिक्री  गुरुजी");
        jMenuItem21.setToolTipText("Sales Master");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem21);

        jMenuItem25.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/price-tag.png"))); // NOI18N
        jMenuItem25.setText("विक्रय मूल्य संपादित करें");
        jMenuItem25.setToolTipText("Edit Selling Price");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem25);

        jMenuItem26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/if_edit-find-replace.png"))); // NOI18N
        jMenuItem26.setText("Sales New1111");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem26);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/sale.png"))); // NOI18N
        jMenuItem13.setText("Sales Page");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem13);

        jMenuBar1.add(jMenu16);

        jMenu8.setEnabled(false);
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu8);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/return.png"))); // NOI18N
        jMenu10.setText("वापसी");
        jMenu10.setMnemonic(KeyEvent.VK_T);
        jMenu10.setToolTipText("Returns");
        jMenu10.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu10.setIconTextGap(1);
        jMenu10.setMaximumSize(new java.awt.Dimension(87, 32000));
        jMenu10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem22.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/return-box.png"))); // NOI18N
        jMenuItem22.setText(" खरीद वापसी");
        jMenuItem22.setToolTipText("Purchase Return");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem22);

        jMenuItem24.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/return.png"))); // NOI18N
        jMenuItem24.setText(" बिक्री वापसी");
        jMenuItem24.setToolTipText("Sales Return");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem24);

        jMenuBar1.add(jMenu10);

        jMenu9.setEnabled(false);
        jMenu9.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu9);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/icons8-combo-chart-85.png"))); // NOI18N
        jMenu5.setText(" रिपोर्ट");
        jMenu5.setToolTipText("Reports");
        jMenu5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setIconTextGap(1);
        jMenu5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu5.setMnemonic(KeyEvent.VK_R);

        jMenuItem15.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/clipboard.png"))); // NOI18N
        jMenuItem15.setText("खरीद  रिपोर्ट");
        jMenuItem15.setToolTipText("Purchase Report");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuItem14.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/analytics (2).png"))); // NOI18N
        jMenuItem14.setText("बिक्री  रिपोर्ट");
        jMenuItem14.setToolTipText("Sales Report");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuItem16.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/analytics (1).png"))); // NOI18N
        jMenuItem16.setText("खरीद वापसी रिपोर्ट ");
        jMenuItem16.setToolTipText("Purchase Return Report");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/analytics 3.png"))); // NOI18N
        jMenuItem17.setText("बिक्री वापसी रिपोर्ट");
        jMenuItem17.setToolTipText("Sale Return Report");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuBar1.add(jMenu5);

        jMenu12.setEnabled(false);
        jMenu12.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu12);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/account.png"))); // NOI18N
        jMenu3.setText("हिसाब किताब");
        jMenu3.setToolTipText("Accounts");
        jMenu3.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setIconTextGap(1);
        jMenu3.setPreferredSize(new java.awt.Dimension(87, 100));
        jMenu3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu3.setMnemonic(KeyEvent.VK_A);

        jMenuItem10.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/cheque.png"))); // NOI18N
        jMenuItem10.setText("वेंडर चेक / एनईएफटी क्लीयरेंस");
        jMenuItem10.setToolTipText("Vendor Cheque Clearance");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/cheque_1.png"))); // NOI18N
        jMenuItem11.setText(" ग्राहक चेक क्लीयरेंस");
        jMenuItem11.setToolTipText("Customer Cheque Clearance");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem9.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/accountant (1).png"))); // NOI18N
        jMenuItem9.setText("विक्रेता खाता");
        jMenuItem9.setToolTipText("Vendor Account");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem23.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/management (1).png"))); // NOI18N
        jMenuItem23.setText(" ग्राहक खाता");
        jMenuItem23.setToolTipText("Customer Account");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem23);

        jMenuBar1.add(jMenu3);

        jMenu19.setEnabled(false);
        jMenu19.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu19);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/sell-stock-85.png"))); // NOI18N
        jMenu4.setText("भण्डार");
        jMenu4.setToolTipText("Stock");
        jMenu4.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setIconTextGap(1);
        jMenu4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu4.setMnemonic(VK_E);
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/groceries_milk.png"))); // NOI18N
        jMenuItem8.setText("Add Opening Stock");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem18.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/groceries (1).png"))); // NOI18N
        jMenuItem18.setText("उत्पाद की उपलब्धता");
        jMenuItem18.setToolTipText("Item Availability");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem18);

        jMenuBar1.add(jMenu4);

        jMenu11.setEnabled(false);
        jMenu11.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu11);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/contact.png"))); // NOI18N
        jMenu13.setText("संपर्क करें");
        jMenu13.setMnemonic(KeyEvent.VK_C);
        jMenu13.setToolTipText("Contact");
        jMenu13.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu13.setIconTextGap(1);
        jMenu13.setPreferredSize(new java.awt.Dimension(87, 100));
        jMenu13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu13MouseClicked(evt);
            }
        });
        jMenu13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu13KeyPressed(evt);
            }
        });

        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App_icons/info.png"))); // NOI18N
        jMenuItem19.setText("Contact Information");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem19);

        jMenuBar1.add(jMenu13);

        jMenu20.setEnabled(false);
        jMenu20.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu20);

        jMenu18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/EOD-90.png"))); // NOI18N
        jMenu18.setText(" दिन के अंत मे");
        jMenu18.setToolTipText("EOD");
        jMenu18.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jMenu18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu18.setIconTextGap(1);
        jMenu18.setMaximumSize(new java.awt.Dimension(100, 32767));
        jMenu18.setPreferredSize(new java.awt.Dimension(87, 100));
        jMenu18.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu18MouseClicked(evt);
            }
        });
        jMenu18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu18KeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu18);

        jMenu21.setEnabled(false);
        jMenu21.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu21);

        jMenu22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Use ICON/clock-alert-icons8--85.png"))); // NOI18N
        jMenu22.setText("चेतावनी समाप्ति तिथि");
        jMenu22.setToolTipText("Alert Exp Item");
        jMenu22.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jMenu22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu22.setIconTextGap(1);
        jMenu22.setPreferredSize(new java.awt.Dimension(87, 100));
        jMenu22.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jMenu22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu22MouseClicked(evt);
            }
        });
        jMenu22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu22KeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu22);

        jMenu24.setEnabled(false);
        jMenu24.setPreferredSize(new java.awt.Dimension(40, 19));
        jMenuBar1.add(jMenu24);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        VendorChequeClearanceView storeDetails = new VendorChequeClearanceView();
        storeDetails.setTitle("Vendor Cheque/NEFT Clearance");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        VendorChequeClearanceView storeDetails = new VendorChequeClearanceView();
        storeDetails.setTitle("Vendor Cheque Clearance");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        SalesReportView storeDetails = new SalesReportView();
       // storeDetails.setTitle("Sales Report");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        PurchaseReportView storeDetails = new PurchaseReportView();
       // storeDetails.setTitle("Purchase Report");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);

//        PurchaseMaster purchaseMaster = new PurchaseMaster(jDesktopPane1);
//        purchaseMaster.setTitle("Item Purchase");
//        jDesktopPane1.add(purchaseMaster);
//        SetDimension setDimension = new SetDimension();
//        setDimension.setInternalFrameLocation(jDesktopPane1, purchaseMaster);
//        purchaseMaster.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AddStockViewNew storeDetails = new AddStockViewNew(jDesktopPane1);
       // AddStockView storeDetails = new AddStockView(jDesktopPane1);
        storeDetails.setTitle("Purchase Items");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);

//        AddStockView storeDetails = new AddStockView(jDesktopPane1);
//        storeDetails.setTitle("Purchase Items");
//        jDesktopPane1.add(storeDetails);
//        SetDimension setDimension = new SetDimension();
//        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
//        storeDetails.setVisible(true);
                // stockAdd.setTitle("Purchase Items");
                // jDesktopPane1.add(stockAdd);
                // SetDimension setDimension = new SetDimension();
              //   setDimension.setInternalFrameLocation(jDesktopPane1, stockAdd);
         //        PurchaseMaster purchaseMaster = new PurchaseMaster(jDesktopPane1);
         //        purchaseMaster.setTitle("Purchase Items");
         //        jDesktopPane1.add(purchaseMaster);
         //        SetDimension setDimension = new SetDimension();
         //        setDimension.setInternalFrameLocation(jDesktopPane1, purchaseMaster);
         //        purchaseMaster.setVisible(true);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        AddOpeningStockView storeDetails = new AddOpeningStockView();
        storeDetails.setTitle("Add Opening Stock");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        VendorAccount storeDetails = new VendorAccount(jDesktopPane1, true);
        //storeDetails.setTitle("Vendor Account");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        VendorAccount storeDetails = new VendorAccount(jDesktopPane1, false);
       // storeDetails.setTitle("Vendor Account");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        PurchaseReturnView storeDetails = new PurchaseReturnView(jDesktopPane1, true);
        storeDetails.setTitle("Purchase Return");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        PurchaseReturnView storeDetails = new PurchaseReturnView(jDesktopPane1, false);
        storeDetails.setTitle("Sales Return");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        PurchaseReturnReportView storeDetails = new PurchaseReturnReportView(true);
        //storeDetails.setTitle("Purchase Return Report");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        PurchaseReturnReportView storeDetails = new PurchaseReturnReportView(false);
        storeDetails.setTitle("Sale Return Report");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
//        ItemAvailabilityView storeDetails = new ItemAvailabilityView();
//        storeDetails.setTitle("Item Availability");
//        jDesktopPane1.add(storeDetails);
//        SetDimension setDimension = new SetDimension();
//        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
//        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        Contact storeDetails = new Contact();
        storeDetails.setTitle("Contact Us");
       // storeDetails.setSize(200, 200);
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        SalesPageView saleMaster = new SalesPageView(jDesktopPane1);
      //  SalesPageView saleMaster = new SalesPageView();
        saleMaster.setTitle("Sales Item");
        jDesktopPane1.add(saleMaster);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, saleMaster);
        saleMaster.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        EditSellingPrice editSellingPrice = new EditSellingPrice();
        //editSellingPrice.setTitle("Edit Selling Price");
        jDesktopPane1.add(editSellingPrice);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, editSellingPrice);
        editSellingPrice.setVisible(true);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed

        SaleWithoutBarcodeView saleWithoutBarcodeView = new SaleWithoutBarcodeView();
        saleWithoutBarcodeView.setVisible(true);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        AddStockViewNew addStockViewNew = new AddStockViewNew(jDesktopPane1);
        addStockViewNew.setTitle("Purchase Payment");
        jDesktopPane1.add(addStockViewNew);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, addStockViewNew);
        addStockViewNew.setVisible(true);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        SalesPageView storeDetails = new SalesPageView(jDesktopPane1);
        storeDetails.setTitle("Sales Page");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //       ItemDetailsView itemDetailsView = new ItemDetailsView();
        //       itemDetailsView.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//        StoreDetailsView storeDetails = new StoreDetailsView();
//        storeDetails.setTitle("Update Store Details");
//        jDesktopPane1.add(storeDetails);
//        SetDimension setDimension = new SetDimension();
//        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
//        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        StoreDetailsView storeDetails = new StoreDetailsView();
        storeDetails.setTitle("Update Store Details");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
//       AddStockViewNew_New addStockViewNew = new AddStockViewNew_New(jDesktopPane1);
//       addStockViewNew.setTitle("Purchase Items");
//        jDesktsetValuesopPane1.add(addStockViewNew);
//        SetDimension setDimension = new SetDimension();
//        setDimension.setInternalFrameLocation(jDesktopPane1, addStockViewNew);
//        addStockViewNew.setVisible(true);
        
        PurchaseStock purchaseStock = new PurchaseStock();
       // AddStockView storeDetails = new AddStockView(jDesktopPane1);
        purchaseStock.setTitle("Purchase Items");
        purchaseStock.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu16MouseClicked
        SaleWithoutBarcodeView saleWithoutBarcodeView = new SaleWithoutBarcodeView();
        saleWithoutBarcodeView.setVisible(true);
    }//GEN-LAST:event_jMenu16MouseClicked

    private void jMenu13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu13KeyPressed
       
    }//GEN-LAST:event_jMenu13KeyPressed

    private void jMenu13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu13MouseClicked
      //  Contact_New storeDetails = new Contact_New();
        Contact storeDetails = new Contact();
        storeDetails.setTitle("Contact Us");
       // storeDetails.setSize(200, 200);
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenu13MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        ItemAvailabilityView storeDetails = new ItemAvailabilityView();
        storeDetails.setTitle("Item Availability");
        jDesktopPane1.add(storeDetails);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, storeDetails);
        storeDetails.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu18MouseClicked
         EOD eOD = new EOD();
       // AddStockView storeDetails = new AddStockView(jDesktopPane1);
        eOD.setTitle("Purchase Items");
        jDesktopPane1.add(eOD);
        SetDimension setDimension = new SetDimension();
        setDimension.setInternalFrameLocation(jDesktopPane1, eOD);
        eOD.setVisible(true);
    }//GEN-LAST:event_jMenu18MouseClicked

    private void jMenu18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu18KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu18KeyPressed

    private void jMenu22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu22MouseClicked
       AlertPage alertPage = new AlertPage();
      alertPage.setVisible(true);
    }//GEN-LAST:event_jMenu22MouseClicked

    private void jMenu22KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu22KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu22KeyPressed

    private void jMenu23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu23MouseClicked
        VendorDetails vendorDetails = new VendorDetails();
        vendorDetails.setVisible(true);
    }//GEN-LAST:event_jMenu23MouseClicked

    private void jMenu23KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu23KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu23KeyPressed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenu15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu15MouseClicked
      AddNewItemsPage addNewItemsPage = new AddNewItemsPage();
      addNewItemsPage.setVisible(true);
    }//GEN-LAST:event_jMenu15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    
}
