/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.view;

import com.grocery.bean.ItemAvailability;
import com.grocery.bean.ItemMaster;
import com.grocery.bean.StockDetails;
import com.grocery.bean.StoreDetails;
import com.grocery.bean.VendorBillMaster;
import com.grocery.bean.VendorMaster;
import com.grocery.bean.VendorPartialPayment;
import com.grocery.query.ItemAvailabilityQuery;
import com.grocery.query.ItemQuery;
import com.grocery.query.StoreDetailsQuery;
import com.grocery.query1.ItemQueryNew;
import com.grocery.query.VendorBillMasterQuery;
import com.grocery.query.VendorPartialPaymentQuery;
import com.grocery.query.VendorQuery;
import com.grocery.query1.ItemAvailabilityQueryNew;
import com.grocery.query1.StockDetailsQueryNew;
import com.grocery.read.MessageFormat;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRException;

public class Payment extends javax.swing.JFrame {

    TableModel jTable1;
    String vendorName;

    private boolean flag;

    private Date date = new Date();
    private JDesktopPane jDesktopPane;
    private JTextFieldDateEditor editor;
    private boolean vendorFlag;
    private boolean newVendorFlag;
    private boolean itemFlag;
    private BigDecimal beginningCash;
    private BigDecimal expenses;
    String venName;
    String gstType;
    String expDate;
    com.toedter.calendar.JDateChooser purDate;

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();

        jPanelTds.setVisible(false);
        jPanelPaymentMode2.setVisible(false);
        partialPayment1.setVisible(false); 
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        save.setVisible(false);
        gstAmount1.setVisible(false);
        jLabel5.setVisible(false);
        fullPayment.setVisible(false);
        save.setVisible(false);
        jLabel6.setVisible(false);
        searchVenBillNo.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelPaymentMode1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        partialPayment1 = new javax.swing.JButton();
        fullPayment1 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        fullPayment = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        paymentMode = new javax.swing.JComboBox<String>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalAmount1 = new javax.swing.JTextField();
        discount1 = new javax.swing.JTextField();
        finalAmount1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel1Date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        vanNname = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        jPanelPaymentMode2 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        cheque = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        bank = new javax.swing.JComboBox<String>();
        chequeDate = new com.toedter.calendar.JDateChooser();
        amount = new javax.swing.JFormattedTextField();
        jPanelTds = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        tdsNo = new javax.swing.JFormattedTextField();
        gstAmount1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchVenBillNo = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelPaymentMode1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bank & Cheque Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        partialPayment1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        partialPayment1.setText("Partial Payment");
        partialPayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partialPayment1ActionPerformed(evt);
            }
        });

        fullPayment1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        fullPayment1.setText(" Payment");
        fullPayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullPayment1ActionPerformed(evt);
            }
        });

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        fullPayment.setBackground(new java.awt.Color(255, 255, 255));
        fullPayment.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        fullPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        fullPayment.setText("Print");
        fullPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fullPayment1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(partialPayment1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(fullPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fullPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(partialPayment1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fullPayment1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );

        jLabel34.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("Payment Mode:");

        paymentMode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paymentMode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "Cash", "Card", "Cheque" }));
        paymentMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentModeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Payment Amount", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel2.setText("Total Amount");

        jLabel3.setText("Final Amount");

        jLabel4.setText("Discount");

        totalAmount1.setBackground(new java.awt.Color(255, 255, 204));
        totalAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAmount1ActionPerformed(evt);
            }
        });

        discount1.setBackground(new java.awt.Color(255, 255, 204));

        finalAmount1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(totalAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discount1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(finalAmount1)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(finalAmount1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(discount1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel29.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Purchase Date:");

        jLabel1Date.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1Date, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel1Date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bank & Cheque Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Amount");

        vanNname.setBackground(new java.awt.Color(255, 255, 204));
        vanNname.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        vanNname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vanNname.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        vanNname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vanNnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                vanNnameFocusLost(evt);
            }
        });
        vanNname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vanNnameKeyReleased(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel38.setText("Name");

        jPanelPaymentMode2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel39.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("Cheque#:");

        cheque.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cheque.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cheque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chequeKeyTyped(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel40.setText("Bank Name:");

        bank.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A.P. Mahesh Co-Op Urban Bank Ltd", "Abhyudaya Co-op Bank Ltd", "Abu Dhabi Commercial Bank", "Ahmedabad Mercantile Co-operative Bank Ltd", "Allahabad Bank", "Andhra Bank", "Apna Sahakari Bank Ltd.", "Axis Bank", "Bank Of America", "Bank Of Bahrain And Kuwait", "Bank Of Baroda", "Bank Of Ceylon", "Bank Of India", "Bank Of Maharashtra", "Bank Of Nova Scotia", "Bank Of Rajasthan Ltd", "Bank Of Tokyo-Mitsubishi UFJ Ltd", "Barclays Bank PLC", "Bassein Catholic Co-Op Bank Ltd", "Bharat Co-operative Bank (Mumbai) Ltd", "Bharat Overseas Bank", "BNP Paribas", "Calyon Bank", "Canara Bank", "Catholic Syrian Bank Ltd", "Central Bank Of India", "Chinatrust Commercial Bank", "Citibank NA", "Citizencredit Co-operative Bank Ltd", "City Union Bank Ltd", "Corporation Bank", "Cosmos Co-operative Bank Ltd.", "Credit Agricole Corp N Invsmnt Bank", "DBS Bank Ltd", "Dena Bank", "Deutsche Bank AG", "Development Credit Bank Limited", "Dhanalakshmi Bank Ltd", "DICGC", "Dombivli Nagari Sahakari Bank Limited", "Federal Bank Ltd", "Firstrand Bank Limited", "Greater Bombay Co-op. Bank Ltd", "HDFC Bank Ltd", "HSBC", "ICICI Bank Ltd", "IDBI Bank Ltd", "Indian Bank", "Indian Overseas Bank", "Indusind Bank Ltd", "ING Vysya Bank Ltd", "Jammu And Kashmir Bank Ltd", "Janakalyan Sahakari Bank Ltd", "Janata Sahakari Bank Ltd (Pune)", "JP Morgan Chase Bank NA", "Kallappanna Awade Ich Janata S Bank", "Kalupur Commercial Co. Op. Bank Ltd.", "Kalyan Janata Sahakari Bank Ltd.", "Kapole Co Op Bank", "Karad Urban Co-Op Bank Ltd", "Karnataka Bank Ltd", "Karnataka State Apex  Coop. Bank Ltd.", "Karur Vysya Bank", "Kotak Mahindra Bank", "Lakshmi Vilas Bank Ltd", "Mahanagar Co-op Bank Ltd", "Maharashtra State Co Operative Bank", "Mashreq Bank PSC", "Mehsana Urban Cooperative Bank Ltd", "Mizuho Corporate Bank Ltd", "Nagpur Nagrik Sahakari Bank Ltd", "Nainital Bank Limited", "Nasik Merchants Co-Op Bank Ltd", "New India Co-operative Bank Ltd", "Nkgsb Co-op Bank Ltd", "Nutan Nagarik Sahakari Bank Ltd", "Oman International Bank Saog", "Oriental Bank Of Commerce", "Parsik Janata Sahakari Bank Ltd", "PMC Bank", "Punjab And Maharashtra Co-op Bank Ltd", "Punjab And Sind Bank", "Punjab National Bank", "Rajkot Nagarik Sahakari Bank Ltd", "Ratnakar Bank Ltd", "Reserve Bank Of India", "Saraswat Co-operative Bank Ltd", "Shamrao Vithal Co-operative Bank Limited", "Shinhan Bank", "Societe Generale", "South Indian Bank", "Standard Chartered Bank", "State Bank Of Bikaner And Jaipur", "State Bank Of Hyderabad", "State Bank Of India", "State Bank Of Indore", "State Bank Of Mauritius Ltd", "State Bank Of Mysore", "State Bank Of Patiala", "State Bank Of Travancore", "Surat Peoples Co-Op Bank Ltd", "Syndicate Bank", "Tamilnad Mercantile Bank Ltd", "Tamilnadu State Apex Cooperative Bank Limited", "Thane Janata Sahakari Bank Ltd", "The Royal Bank Of Scotland NV", "UBS AG", "UCO Bank", "Union Bank Of India", "United Bank Of India", "Vijaya Bank", "West Bengal State Cooperative Bank Ltd", "Yes Bank Ltd" }));

        chequeDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanelPaymentMode2Layout = new javax.swing.GroupLayout(jPanelPaymentMode2);
        jPanelPaymentMode2.setLayout(jPanelPaymentMode2Layout);
        jPanelPaymentMode2Layout.setHorizontalGroup(
            jPanelPaymentMode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMode2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPaymentMode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPaymentMode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPaymentMode2Layout.createSequentialGroup()
                        .addComponent(cheque)
                        .addGap(10, 10, 10)
                        .addComponent(chequeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bank, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanelPaymentMode2Layout.setVerticalGroup(
            jPanelPaymentMode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMode2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPaymentMode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cheque)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentMode2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelPaymentMode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chequeDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelPaymentMode2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bank))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        amount.setBackground(new java.awt.Color(255, 255, 204));
        amount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountFocusLost(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountKeyReleased(evt);
            }
        });

        jPanelTds.setBackground(new java.awt.Color(255, 255, 255));

        jLabel41.setFont(new java.awt.Font("Georgia", 1, 10)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel41.setText("TDS Number");

        tdsNo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tdsNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tdsNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tdsNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tdsNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tdsNoFocusLost(evt);
            }
        });
        tdsNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdsNoActionPerformed(evt);
            }
        });
        tdsNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tdsNoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelTdsLayout = new javax.swing.GroupLayout(jPanelTds);
        jPanelTds.setLayout(jPanelTdsLayout);
        jPanelTdsLayout.setHorizontalGroup(
            jPanelTdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTdsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addGap(54, 54, 54)
                .addComponent(tdsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanelTdsLayout.setVerticalGroup(
            jPanelTdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTdsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTdsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPaymentMode2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(vanNname, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanelPaymentMode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTds, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vanNname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        gstAmount1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setText("GST Amount");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Vendor Name Contact Number Bill No");

        searchVenBillNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchVenBillNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPaymentMode1Layout = new javax.swing.GroupLayout(jPanelPaymentMode1);
        jPanelPaymentMode1.setLayout(jPanelPaymentMode1Layout);
        jPanelPaymentMode1Layout.setHorizontalGroup(
            jPanelPaymentMode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPaymentMode1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchVenBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(jPanelPaymentMode1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gstAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(paymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPaymentMode1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPaymentMode1Layout.setVerticalGroup(
            jPanelPaymentMode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMode1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPaymentMode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(searchVenBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPaymentMode1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gstAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPaymentMode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPaymentMode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void paymentModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentModeActionPerformed
        cheque.setText("");
        //        chequeDate.setDate(date);
        bank.setSelectedIndex(0);
        if (paymentMode.getSelectedIndex() == 0 || paymentMode.getSelectedIndex() == 1) {
            jPanelPaymentMode2.setVisible(false);
            jPanelTds.setVisible(false);

        } else if (paymentMode.getSelectedIndex() == 2) {
            bank.setSelectedIndex(0);
            jPanelTds.setVisible(false);
            jPanelPaymentMode2.setVisible(false);
            chequeDate.setVisible(false);
            
        } else if (paymentMode.getSelectedIndex() == 3) {
            jPanelTds.setVisible(false);
            jPanelPaymentMode2.setVisible(true);
            chequeDate.setVisible(true);
        } else {
            jPanelTds.setVisible(true);
            jPanelPaymentMode2.setVisible(false);
            //chequeDate.setVisible(true);
        }
    }//GEN-LAST:event_paymentModeActionPerformed

    private void fullPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullPaymentActionPerformed
        // pay();
    }//GEN-LAST:event_fullPaymentActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // save();
    }//GEN-LAST:event_saveActionPerformed

    private void totalAmount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAmount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmount1ActionPerformed

    private void partialPayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partialPayment1ActionPerformed
        PartialPaymentView1 partialPaymentView1 = new PartialPaymentView1();
        partialPaymentView1.setVisible(true);
    }//GEN-LAST:event_partialPayment1ActionPerformed

    private void fullPayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullPayment1ActionPerformed
   try {
            fullPayment();
        } catch (SQLException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fullPayment1ActionPerformed

    private void vanNnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vanNnameFocusGained
        vanNname.selectAll();
    }//GEN-LAST:event_vanNnameFocusGained

    private void vanNnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vanNnameFocusLost
        if (vanNname.getText().trim().isEmpty()) {
            vanNname.setText("0.00");
        }
    }//GEN-LAST:event_vanNnameFocusLost

    private void vanNnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vanNnameKeyReleased
        /* if(!(amount.getText().trim().isEmpty()))
         getFinalAmountPaid(amount.getText());
         else
         finalAmountPaid.setText("0.00");
         */
        
    }//GEN-LAST:event_vanNnameKeyReleased

    private void chequeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chequeKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_chequeKeyTyped

    private void searchVenBillNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchVenBillNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchVenBillNoActionPerformed

    private void amountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFocusGained

    private void amountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFocusLost

    private void amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_amountKeyReleased

    private void tdsNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdsNoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tdsNoFocusGained

    private void tdsNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdsNoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tdsNoFocusLost

    private void tdsNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdsNoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tdsNoKeyReleased

    private void tdsNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdsNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdsNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField amount;
    private javax.swing.JComboBox<String> bank;
    private javax.swing.JTextField cheque;
    private com.toedter.calendar.JDateChooser chequeDate;
    private javax.swing.JTextField discount1;
    private javax.swing.JTextField finalAmount1;
    private javax.swing.JButton fullPayment;
    private javax.swing.JButton fullPayment1;
    private javax.swing.JTextField gstAmount1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelPaymentMode1;
    private javax.swing.JPanel jPanelPaymentMode2;
    private javax.swing.JPanel jPanelTds;
    private javax.swing.JButton partialPayment1;
    private javax.swing.JComboBox<String> paymentMode;
    private javax.swing.JButton save;
    private javax.swing.JTextField searchVenBillNo;
    private javax.swing.JFormattedTextField tdsNo;
    private javax.swing.JTextField totalAmount1;
    private javax.swing.JFormattedTextField vanNname;
    // End of variables declaration//GEN-END:variables
    public void setValues(com.toedter.calendar.JDateChooser purDate, String totalAmount, String discountAmount, String finalAmount, TableModel tableData, String vendorName1, String gstType) {
        totalAmount1.setText((totalAmount));
       // gstAmount1.setText((gstAmount2));
        finalAmount1.setText((finalAmount));
        discount1.setText((discountAmount));
        vanNname.setText((vendorName1));
        this.jTable1 = tableData;
        venName = vendorName1;
        this.gstType = gstType;
        this.purDate = purDate;
        jLabel1Date.setText(purDate.getDate().toString());
        amount.setText(finalAmount);
    }

    private Date getDate() throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String sdate = sdf.format(new Date());
        return sdf.parse(sdate);
    }

    public void addStock() throws ParseException {
          String paymentMode = this.paymentMode.getSelectedItem().toString();
        if (paymentMode.equalsIgnoreCase("--Select--")) {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please select a paymentMode"), "Error message", JOptionPane.ERROR_MESSAGE);
            this.paymentMode.requestFocus();
            return;
        }
        DefaultTableModel tm = (DefaultTableModel) this.jTable1;
        String itemName = "";
        String hsnCode;
        BigDecimal quantity;
        BigDecimal total;
        BigDecimal unitPrice;
        BigDecimal gstPercent;
        BigDecimal gstAmount;
        BigDecimal finalTotal;
        BigDecimal sellingUnit;
        String remark;
        String type;
        Date mfg;
        Date exp;
        BigDecimal discount;
       // BigDecimal mrp;

        VendorPartialPayment vendorPartialPayment = new VendorPartialPayment();

        
        ItemMaster purchaseMaster = new ItemMaster();
        ItemQueryNew itemQueryNew = new ItemQueryNew();

        StoreDetails storeDetails;
        StoreDetailsQuery storeDetailsQuery = new StoreDetailsQuery();
        List<StoreDetails> storelist = storeDetailsQuery.getStoreDetails();
        storeDetails = storelist.get(0);
        VendorMaster vendorMaster;

        ItemAvailability itemAvailability = new ItemAvailability();
        ItemAvailabilityQueryNew itemAvailabilityQueryNew = new ItemAvailabilityQueryNew();

        StockDetails stockDetails = new StockDetails();
        StockDetailsQueryNew stockDetailsQueryNew = new StockDetailsQueryNew();

        
        VendorBillMasterQuery vendorBillMasterQueryNew = new VendorBillMasterQuery();
        VendorQuery vendorQuery = new VendorQuery();
        vendorMaster = vendorQuery.getVendorByName(venName);

        VendorBillMaster vendorBillMaster = new VendorBillMaster();

        vendorBillMaster.setDate(new Date(new SimpleDateFormat("dd/MM/yyyy").format(purDate.getDate())));
        // vendorBillMaster.setVendorMaster(vendorMaster);
        vendorBillMaster.setVendorMaster(vendorMaster);
        vendorBillMaster.setBillAmount(new BigDecimal(totalAmount1.getText()));
        vendorBillMaster.setChallan("NA");
        vendorBillMaster.setDiscount(new BigDecimal(discount1.getText()));
        vendorBillMaster.setFinalBillAmount(new BigDecimal(finalAmount1.getText()));

        vendorBillMaster.setRemark(gstType);

        vendorBillMaster.setReference("Direct");

        vendorBillMaster.setStoreDetails(storeDetails);
        //vendorBillMaster.setStockDetailses(new HashSet(stocklist));
        vendorMaster = vendorQuery.getVendorByName(venName);

        vendorBillMaster.setVendorMaster(vendorMaster);
        vendorBillMasterQueryNew.insertIntoVendorBillMaster(vendorBillMaster);
        
        
        int i = 0;
        while (i < tm.getRowCount()) {

            itemName = jTable1.getValueAt(i, 0).toString();
            hsnCode = jTable1.getValueAt(i, 1).toString();
            quantity = new BigDecimal(tm.getValueAt(i, 2).toString());
            total = new BigDecimal(tm.getValueAt(i, 3).toString());
            unitPrice = new BigDecimal(tm.getValueAt(i, 4).toString());
            gstPercent = new BigDecimal(tm.getValueAt(i, 5).toString());
            gstAmount = new BigDecimal(tm.getValueAt(i, 6).toString());
            finalTotal = new BigDecimal(tm.getValueAt(i, 7).toString());
            sellingUnit = new BigDecimal(tm.getValueAt(i, 8).toString());
            remark = tm.getValueAt(i, 9).toString();
            type = tm.getValueAt(i, 9).toString();
            mfg = new Date(tm.getValueAt(i, 10).toString());
            exp = new Date(tm.getValueAt(i, 11).toString());
          //  mrp = new BigDecimal(tm.getValueAt(i ,12).toString());
            
            purchaseMaster.setName(itemName);
            purchaseMaster.setBrand(hsnCode);
            purchaseMaster.setWeight(unitPrice);
            purchaseMaster.setUnitPrice(unitPrice);
            purchaseMaster.setQuantity(sellingUnit); 
          //  purchaseMaster.setTotal(sellingUnit);
            purchaseMaster.setGstType(gstType);
            
            purchaseMaster.setGstPercent(sellingUnit);
//            purchaseMaster.setGstAmount(sellingUnit);
//            purchaseMaster.setActualAmount(mfg);
//         
//             purchaseMaster.setVendorId(exp);
           // purchaseMaster.setMrp(mrp);

            List<ItemMaster> itemList = itemQueryNew.checkItem(purchaseMaster);
            if (itemList.isEmpty()) {
                itemQueryNew.insertItem(purchaseMaster);
            } else {
                for (ItemMaster im : itemList) {
                    purchaseMaster.setId(im.getId());
                }
            }

            stockDetails.setItemMaster(purchaseMaster);
            stockDetails.setQuantity(quantity);
            stockDetails.setUnitPrice(unitPrice);

            if (type.equals("GST")) {
                stockDetails.setGstPercent(gstPercent);
                stockDetails.setGstAmount(gstAmount);
                stockDetails.setIgstPercent(new BigDecimal(0.00));
                stockDetails.setIgstAmount((new BigDecimal(0.00)));
            } else if (type.equals("IGST")) {
                stockDetails.setGstPercent((new BigDecimal(0.00)));
                stockDetails.setGstAmount((new BigDecimal(0.00)));
                stockDetails.setIgstPercent(gstPercent);
                stockDetails.setIgstAmount(gstAmount);
            } else {
                stockDetails.setIgstPercent(new BigDecimal(0.00));
                stockDetails.setIgstAmount(new BigDecimal(0.00));
                stockDetails.setGstPercent((new BigDecimal(0.00)));
                stockDetails.setGstAmount((new BigDecimal(0.00)));
            }

            stockDetails.setFinalTotal(finalTotal);
            stockDetails.setVendorBillMaster(vendorBillMaster);
            stockDetailsQueryNew.insertIntoStockDetails(stockDetails);
            BigDecimal thresholdPercent = new BigDecimal(0.25);

            itemAvailability.setItemMaster(purchaseMaster);
            itemAvailability.setAvailability(quantity);
            itemAvailability.setThreshold(thresholdPercent.multiply(quantity));
            List<ItemAvailability> itemAvailabilityList = itemAvailabilityQueryNew.checkItem(itemAvailability);

            if (itemAvailabilityList.isEmpty()) {
                itemAvailabilityQueryNew.insertIntoItemAvailability(itemAvailability);
            } else {
                for (ItemAvailability ia : itemAvailabilityList) {
                    itemAvailability.setId(ia.getId());
                    itemAvailability.setAvailability(ia.getAvailability().add(quantity));
                    itemAvailability.setThreshold(thresholdPercent.multiply(ia.getAvailability().add(quantity)));
                    itemAvailabilityQueryNew.updateItemAvailability(itemAvailability);
                }
            }
            i++;
        }

      

        
        
        String chequeNumber = cheque.getText();
        String sudexo = tdsNo.getText();
        
        String bankName = bank.getSelectedItem().toString();
        String status = "";

        vendorPartialPayment.setDate(new Date(new SimpleDateFormat("dd/MM/yyyy").format(purDate.getDate())));
        vendorPartialPayment.setVendorMaster(vendorMaster);
        vendorPartialPayment.setPaidAmount(new BigDecimal(amount.getText().trim()).subtract(new BigDecimal(discount1.getText())));
        vendorPartialPayment.setPaymentMode(paymentMode);
       // vendorPartialPayment.setChequeCardNumber(cheque);
        vendorPartialPayment.setChequeCardNumber(chequeNumber);
        vendorPartialPayment.setChequeDate(chequeDate.getDate());
        vendorPartialPayment.setBank(bankName);
        vendorPartialPayment.setStatus(status);
        VendorPartialPaymentQuery vendorPartialPaymentQuery = new VendorPartialPaymentQuery();
        vendorPartialPaymentQuery.insertIntoVendorPartialPayment(vendorPartialPayment);
        JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Sale successful"));
        this.dispose();
    }

    private void insertVendorPaymentDetails() throws ParseException {
        boolean flag = false;
        String bankName = bank.getSelectedItem().toString();
        double finalamount = Double.valueOf(finalAmount1.getText().trim());
        String chequeNo;
        Date chequedate;
        Date purchasedate;
        String chequeAmount;
        String chequeName;
        String chequeNumber = this.cheque.getText().toString();

        VendorQuery vendorQuery = new VendorQuery();
        VendorMaster vendorMaster = vendorQuery.getVendorByName(venName);
        VendorPartialPayment vendorPartialPayment = new VendorPartialPayment();
        String paymentMode = this.paymentMode.getSelectedItem().toString();

        if (paymentMode.equalsIgnoreCase("--select--")) {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please select the payment mode"), "Error message", JOptionPane.ERROR_MESSAGE);
            this.paymentMode.requestFocus();
            return;
        }
        if (paymentMode.equalsIgnoreCase("card")) {
            if (cheque.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please enter the Card number"), "Error message", JOptionPane.ERROR_MESSAGE);
                cheque.requestFocus();
                return;
            }
            chequeNumber = cheque.getText().trim();
        }
        if (paymentMode.equalsIgnoreCase("cheque") || paymentMode.equalsIgnoreCase("neft")) {
            if (cheque.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Please enter the Cheque/NEFT number"), "Error message", JOptionPane.ERROR_MESSAGE);
                cheque.requestFocus();
                return;
            }

            chequeNumber = cheque.getText();
            chequedate = chequeDate.getDate();
            chequeAmount = amount.getText().trim();
            chequeName = vanNname.getText().toString();
            vendorPartialPayment.setBank(bankName);
            vendorPartialPayment.setChequeCardNumber(chequeNumber);
            vendorPartialPayment.setChequeDate(chequedate);
            vendorPartialPayment.setVendorMaster(vendorQuery.getVendorByName(chequeName));
            vendorPartialPayment.setStatus("1");
            vendorPartialPayment.setPaidAmount(BigDecimal.valueOf(finalamount));
            vendorPartialPayment.setPaymentType("Full");
            vendorPartialPayment.setDate(new Date());
            vendorQuery.savePaymentDetails(vendorPartialPayment);
            vendorQuery.insertVendor(vendorPartialPayment);
        }
    }
    private Date getDate1() throws ParseException {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String sdate = sdf.format(new Date());
        return sdf.parse(sdate);
    }

    private void fullPayment() throws SQLException, ClassNotFoundException, JRException {
        try {
            addStock();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, MessageFormat.getMessage("Stock Details failed to save"), "Error Mesage", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private ItemMaster checkItemAndInsert(String itemName, ItemMaster purchaseMaster) {
        ItemMaster item;
        List<ItemMaster> itemList = ItemQuery.getItemByNameAndBrand(itemName);
        ItemQuery itemQuery = new ItemQuery();

        if (itemList.isEmpty()) {
            itemQuery.insertItem(purchaseMaster);
            itemList = ItemQuery.getItemByNameAndBrand(itemName);
            item = itemList.get(0);
        } else {
            item = itemList.get(0);
        }
        return item;
    }

    private void addItemAvailability(ItemMaster item, BigDecimal paidAmount) {
        ItemAvailabilityQuery itemAvailabilityQuery = new ItemAvailabilityQuery();
        ItemAvailability itemAvailability = new ItemAvailability();
        itemAvailability.setItemMaster(item);
        itemAvailability.setAvailability(paidAmount);

        if (!isExist(item)) {
            itemAvailabilityQuery.insertIntoItemAvailability(itemAvailability);
        } else {
            List<ItemAvailability> itemAvailabilityList = (List<ItemAvailability>) itemAvailabilityQuery.checkItem(itemAvailability);
            Object obj = itemAvailabilityList.get(0);
            ItemMaster itemDetails = (ItemMaster) obj;
            Set<ItemAvailability> itemAvailabilityList1 = itemDetails.getItemAvailabilities();
            itemAvailability = itemAvailabilityList1.iterator().next();
            String olditem = String.valueOf(itemAvailability.getAvailability());
            double oitem = Double.valueOf(olditem);
            itemAvailability.setAvailability(BigDecimal.valueOf(oitem));
            itemAvailabilityQuery.updateItemAvailability(itemAvailability);
        }
    }

    private boolean isExist(ItemMaster item) {
        boolean exist = true;
        ItemAvailabilityQuery itemAvailabilityQuery = new ItemAvailabilityQuery();
        List<ItemAvailability> list = itemAvailabilityQuery.checkItem(item);
        if (list.isEmpty()) {
            exist = false;
        }
        return exist;
    }

   

}
